workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Spaire-OAS:
        inputs:
            - location: https://api.spaire.com/openapi.json
        overlays:
            - location: https://raw.githubusercontent.com/Spaire-Tech/spaire-ruby/main/sdk/overlays/security.yml
            - location: https://raw.githubusercontent.com/Spaire-Tech/spaire-ruby/main/sdk/overlays/type_parameter.yml
            - location: https://raw.githubusercontent.com/Spaire-Tech/spaire-ruby/main/sdk/overlays/product_price_discriminator.yml
            - location: https://raw.githubusercontent.com/Spaire-Tech/spaire-ruby/main/sdk/overlays/read_only.yml
        registry:
            location: registry.speakeasyapi.dev/spaire/spaire/spaire-oas
targets:
    spaire:
        target: ruby
        source: Spaire-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/spaire/spaire/spaire-api-ruby-code-samples
            blocking: false
