# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require "faraday"
require "faraday/multipart"
require "faraday/retry"
require "sorbet-runtime"

require_relative "sdk_hooks/hooks"
require_relative "utils/retries"

module OpenApiSDK
  extend T::Sig

  class Spaire
    extend T::Sig

    attr_accessor(
      :organizations,
      :subscriptions,
      :oauth2,
      :benefits,
      :benefit_grants,
      :webhooks,
      :products,
      :orders,
      :client_invoices,
      :refunds,
      :disputes,
      :checkouts,
      :files,
      :metrics,
      :license_keys,
      :checkout_links,
      :custom_fields,
      :discounts,
      :customers,
      :members,
      :customer_portal,
      :customer_seats,
      :customer_sessions,
      :member_sessions,
      :events,
      :event_types,
      :meters,
      :organization_access_tokens,
      :customer_meters,
      :payments
    )

    # Instantiates the SDK, configuring it with the provided parameters.
    #
    # @param client [Faraday::Connection, nil] The faraday HTTP client to use for all operations
    # @param retry_config [::OpenApiSDK::Utils::RetryConfig, nil] The retry configuration to use for all operations
    # @param timeout_ms [Integer, nil] Request timeout in milliseconds for all operations
    # @param security [Models::Components::Security, nil] The security details required for authentication
    # @param security_source [Proc{|| Models::Components::Security, nil}] A function that returns security details required for authentication
    # @param server [Symbol, nil] The server identifier to use for all operations
    # @param server_url [String, nil] The server URL to use for all operations
    # @param url_params [Hash{Symbol => String}, nil] Parameters to optionally template the server URL with
    sig do
      params(
        client: T.nilable(Faraday::Connection),
        retry_config: T.nilable(::OpenApiSDK::Utils::RetryConfig),
        timeout_ms: T.nilable(Integer),
        access_token: T.nilable(::String),
        security_source: T.nilable(T.proc.returns(Models::Components::Security)),
        server: T.nilable(Symbol),
        server_url: T.nilable(String),
        url_params: T.nilable(T::Hash[Symbol, String])
      )
        .void
    end
    def initialize(
      client: nil,
      retry_config: nil,
      timeout_ms: nil,
      access_token: nil,
      security_source: nil,
      server: nil,
      server_url: nil,
      url_params: nil
    )

      connection_options = {
        request: {
          params_encoder: Faraday::FlatParamsEncoder
        }
      }
      connection_options[:request][:timeout] = (timeout_ms.to_f / 1000) unless timeout_ms.nil?

      client ||= Faraday.new(**connection_options) do |f|
        f.request(:multipart, {flat_encode: true})
        # f.response :logger, nil, { headers: true, bodies: true, errors: true }
      end

      if !server_url.nil?
        if !url_params.nil?
          server_url = Utils.template_url(server_url, url_params)
        end
      end

      raise StandardError, "Invalid server \"#{server}\"" if !server.nil? && !SERVERS.key?(server)
      hooks = SDKHooks::Hooks.new
      @sdk_configuration = SDKConfiguration.new(
        client,
        hooks,
        retry_config,
        timeout_ms,
        access_token,
        security_source,
        server_url,
        server
      )
      @sdk_configuration = hooks.sdk_init(config: @sdk_configuration)
      init_sdks
    end

    sig { void }
    def init_sdks
      @organizations = Organizations.new(@sdk_configuration)
      @subscriptions = Subscriptions.new(@sdk_configuration)
      @oauth2 = Oauth2.new(@sdk_configuration)
      @benefits = Benefits.new(@sdk_configuration)
      @benefit_grants = BenefitGrants.new(@sdk_configuration)
      @webhooks = Webhooks.new(@sdk_configuration)
      @products = Products.new(@sdk_configuration)
      @orders = Orders.new(@sdk_configuration)
      @client_invoices = ClientInvoices.new(@sdk_configuration)
      @refunds = Refunds.new(@sdk_configuration)
      @disputes = Disputes.new(@sdk_configuration)
      @checkouts = Checkouts.new(@sdk_configuration)
      @files = Files.new(@sdk_configuration)
      @metrics = Metrics.new(@sdk_configuration)
      @license_keys = LicenseKeys.new(@sdk_configuration)
      @checkout_links = CheckoutLinks.new(@sdk_configuration)
      @custom_fields = CustomFields.new(@sdk_configuration)
      @discounts = Discounts.new(@sdk_configuration)
      @customers = Customers.new(@sdk_configuration)
      @members = Members.new(@sdk_configuration)
      @customer_portal = CustomerPortal.new(@sdk_configuration)
      @customer_seats = CustomerSeats.new(@sdk_configuration)
      @customer_sessions = CustomerSessions.new(@sdk_configuration)
      @member_sessions = MemberSessions.new(@sdk_configuration)
      @events = Events.new(@sdk_configuration)
      @event_types = EventTypes.new(@sdk_configuration)
      @meters = Meters.new(@sdk_configuration)
      @organization_access_tokens = OrganizationAccessTokens.new(@sdk_configuration)
      @customer_meters = CustomerMeters.new(@sdk_configuration)
      @payments = Payments.new(@sdk_configuration)
    end

    sig { params(base_url: String, url_variables: T.nilable(T::Hash[Symbol, T.any(String, T::Enum)])).returns(String) }
    def get_url(base_url:, url_variables: nil)
      sd_base_url, sd_options = @sdk_configuration.get_server_details

      if base_url.nil?
        base_url = sd_base_url
      end

      if url_variables.nil?
        url_variables = sd_options
      end

      return Utils.template_url(base_url, url_variables)
    end

  end
end
