# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class Address
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :country,
          Models::Components::CountryAlpha2,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("country"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::CountryAlpha2, false)
            }
          }
        )

        field(
          :line1,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("line1")}}
        )

        field(
          :line2,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("line2")}}
        )

        field(
          :postal_code,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("postal_code")}}
        )

        field(
          :city,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("city")}}
        )

        field(
          :state,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("state")}}
        )

        sig {
          params(
            country: Models::Components::CountryAlpha2,
            line1: T.nilable(::String),
            line2: T.nilable(::String),
            postal_code: T.nilable(::String),
            city: T.nilable(::String),
            state: T.nilable(::String)
          )
            .void
        }
        def initialize(country:, line1: nil, line2: nil, postal_code: nil, city: nil, state: nil)
          @country = country
          @line1 = line1
          @line2 = line2
          @postal_code = postal_code
          @city = city
          @state = state
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @country == other.country
          return false unless @line1 == other.line1
          return false unless @line2 == other.line2
          return false unless @postal_code == other.postal_code
          return false unless @city == other.city
          return false unless @state == other.state
          true
        end
      end
    end
  end
end
