# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class BalanceCreditOrderMetadata
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :order_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("order_id"), required: true}}
        )

        field(
          :amount,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("amount"), required: true}}
        )

        field(
          :currency,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("currency"), required: true}}
        )

        field(
          :tax_amount,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("tax_amount"), required: true}}
        )

        field :fee, ::Integer, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("fee"), required: true}}

        field(
          :product_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("product_id")}}
        )

        field(
          :subscription_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("subscription_id")}}
        )

        field(
          :tax_state,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("tax_state")}}
        )

        field(
          :tax_country,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("tax_country")}}
        )

        sig {
          params(
            order_id: ::String,
            amount: ::Integer,
            currency: ::String,
            tax_amount: ::Integer,
            fee: ::Integer,
            product_id: T.nilable(::String),
            subscription_id: T.nilable(::String),
            tax_state: T.nilable(::String),
            tax_country: T.nilable(::String)
          )
            .void
        }
        def initialize(
          order_id:,
          amount:,
          currency:,
          tax_amount:,
          fee:,
          product_id: nil,
          subscription_id: nil,
          tax_state: nil,
          tax_country: nil
        )
          @order_id = order_id
          @amount = amount
          @currency = currency
          @tax_amount = tax_amount
          @fee = fee
          @product_id = product_id
          @subscription_id = subscription_id
          @tax_state = tax_state
          @tax_country = tax_country
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @order_id == other.order_id
          return false unless @amount == other.amount
          return false unless @currency == other.currency
          return false unless @tax_amount == other.tax_amount
          return false unless @fee == other.fee
          return false unless @product_id == other.product_id
          return false unless @subscription_id == other.subscription_id
          return false unless @tax_state == other.tax_state
          return false unless @tax_country == other.tax_country
          true
        end
      end
    end
  end
end
