# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Properties to create a benefit of type `github_repository`.
      class BenefitGitHubRepositoryCreateProperties
        extend T::Sig
        include Crystalline::MetadataFields

        # The owner of the repository.
        field(
          :repository_owner,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("repository_owner"), required: true}}
        )
        # The name of the repository.
        field(
          :repository_name,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("repository_name"), required: true}}
        )
        # The permission level to grant. Read more about roles and their permissions on [GitHub documentation](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role).
        field(
          :permission,
          Models::Components::BenefitGitHubRepositoryCreatePropertiesPermission,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("permission"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.enum_from_string(
                Models::Components::BenefitGitHubRepositoryCreatePropertiesPermission,
                false
              )
            }
          }
        )

        sig {
          params(
            repository_owner: ::String,
            repository_name: ::String,
            permission: Models::Components::BenefitGitHubRepositoryCreatePropertiesPermission
          )
            .void
        }
        def initialize(repository_owner:, repository_name:, permission:)
          @repository_owner = repository_owner
          @repository_name = repository_name
          @permission = permission
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @repository_owner == other.repository_owner
          return false unless @repository_name == other.repository_name
          return false unless @permission == other.permission
          true
        end
      end
    end
  end
end
