# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class BenefitLicenseKeyExpirationProperties
        extend T::Sig
        include Crystalline::MetadataFields

        field :ttl, ::Integer, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("ttl"), required: true}}

        field(
          :timeframe,
          Models::Components::Timeframe,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("timeframe"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::Timeframe, false)
            }
          }
        )

        sig { params(ttl: ::Integer, timeframe: Models::Components::Timeframe).void }
        def initialize(ttl:, timeframe:)
          @ttl = ttl
          @timeframe = timeframe
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @ttl == other.ttl
          return false unless @timeframe == other.timeframe
          true
        end
      end
    end
  end
end
