# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class BenefitDiscordUpdate
        extend T::Sig
        include Crystalline::MetadataFields

        # Key-value object allowing you to store additional information.
        #
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        #
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        #
        # You can store up to **50 key-value pairs**.
        field(
          :metadata,
          Crystalline::Nilable.new(
            Crystalline::Hash.new(
              Symbol,
              Crystalline::Union.new(::String, ::Integer, ::Float, Crystalline::Boolean.new)
            )
          ),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("metadata")}}
        )

        field :type, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("type"), required: true}}
        # The description of the benefit. Will be displayed on products having this benefit.
        field(
          :description,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("description")}}
        )

        field(
          :properties,
          Crystalline::Nilable.new(Models::Components::BenefitDiscordCreateProperties),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("properties")}}
        )

        sig {
          params(
            metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]),
            type: ::String,
            description: T.nilable(::String),
            properties: T.nilable(Models::Components::BenefitDiscordCreateProperties)
          )
            .void
        }
        def initialize(metadata: nil, type: "discord", description: nil, properties: nil)
          @metadata = metadata
          unless type == "discord"
            raise ArgumentError, "Invalid value for type"
          end

          @type = "discord"
          @description = description
          @properties = properties
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @metadata == other.metadata
          return false unless @type == other.type
          return false unless @description == other.description
          return false unless @properties == other.properties
          true
        end
      end
    end
  end
end
