# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Properties to create a benefit of type `discord`.
      class BenefitDiscordCreateProperties
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :guild_token,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("guild_token"), required: true}}
        )
        # The ID of the Discord role to grant.
        field(
          :role_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("role_id"), required: true}}
        )
        # Whether to kick the member from the Discord server on revocation.
        field(
          :kick_member,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("kick_member"), required: true}}
        )

        sig { params(guild_token: ::String, role_id: ::String, kick_member: T::Boolean).void }
        def initialize(guild_token:, role_id:, kick_member:)
          @guild_token = guild_token
          @role_id = role_id
          @kick_member = kick_member
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @guild_token == other.guild_token
          return false unless @role_id == other.role_id
          return false unless @kick_member == other.kick_member
          true
        end
      end
    end
  end
end
