# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class BenefitDownloadablesSubscriberProperties
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :active_files,
          Crystalline::Array.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("active_files"), required: true}}
        )

        sig { params(active_files: T::Array[::String]).void }
        def initialize(active_files:)
          @active_files = active_files
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @active_files == other.active_files
          true
        end
      end
    end
  end
end
