# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Properties for creating a benefit of type `meter_unit`.
      class BenefitMeterCreditCreateProperties
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :units,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("units"), required: true}}
        )

        field(
          :rollover,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("rollover"), required: true}}
        )

        field(
          :meter_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("meter_id"), required: true}}
        )

        sig { params(units: ::Integer, rollover: T::Boolean, meter_id: ::String).void }
        def initialize(units:, rollover:, meter_id:)
          @units = units
          @rollover = rollover
          @meter_id = meter_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @units == other.units
          return false unless @rollover == other.rollover
          return false unless @meter_id == other.meter_id
          true
        end
      end
    end
  end
end
