# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class BenefitDownloadablesProperties
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :archived,
          Crystalline::Hash.new(Symbol, Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("archived"), required: true}}
        )

        field(
          :files,
          Crystalline::Array.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("files"), required: true}}
        )

        sig { params(archived: T::Hash[Symbol, T::Boolean], files: T::Array[::String]).void }
        def initialize(archived:, files:)
          @archived = archived
          @files = files
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @archived == other.archived
          return false unless @files == other.files
          true
        end
      end
    end
  end
end
