# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class BodyCustomerPortalCommunityUploadPostImage
        extend T::Sig
        include Crystalline::MetadataFields

        field :file, Models::Components::File, {'multipart_form': {'file': true, 'field_name': "file"}}

        sig { params(file: Models::Components::File).void }
        def initialize(file:)
          @file = file
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @file == other.file
          true
        end
      end
    end
  end
end
