# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class ClientInvoiceStatus
        include ::Crystalline::Enum
        enums do
          DRAFT = new("draft")
          OPEN = new("open")
          PAID = new("paid")
          VOID = new("void")
          UNCOLLECTIBLE = new("uncollectible")
        end

        open!
      end
    end
  end
end
