# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CommunityCommentRead
        extend T::Sig
        include Crystalline::MetadataFields

        # Creation timestamp of the object.
        field(
          :created_at,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("created_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        field :id, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("id"), required: true}}

        field(
          :post_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("post_id"), required: true}}
        )

        field(
          :author,
          Crystalline::DiscriminatedUnion.new(
            "kind",
            {
              "instructor" => Models::Components::CommunityAuthorInstructor,
              "student" => Models::Components::CommunityAuthorStudent
            }
          ),
          {
            'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("author"), required: true},
            'discriminator': "kind",
            'discriminator_mapping': {
              "instructor" => Models::Components::CommunityAuthorInstructor,
              "student" => Models::Components::CommunityAuthorStudent
            }
          }
        )

        field(
          :content,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("content"), required: true}}
        )
        # Last modification timestamp of the object.
        field(
          :modified_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("modified_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        field(
          :parent_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("parent_id"), required: true}}
        )

        field(
          :reactions,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::CommunityReactionSummaryEntry)),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("reactions")}}
        )

        field(
          :timestamp_seconds,
          Crystalline::Nilable.new(::Integer),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("timestamp_seconds")}}
        )

        field(
          :deleted,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("deleted")}}
        )

        field(
          :is_own,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("is_own")}}
        )

        sig {
          params(
            created_at: ::DateTime,
            id: ::String,
            post_id: ::String,
            author: T.any(Models::Components::CommunityAuthorInstructor, Models::Components::CommunityAuthorStudent),
            content: ::String,
            modified_at: T.nilable(::DateTime),
            parent_id: T.nilable(::String),
            reactions: T.nilable(T::Array[Models::Components::CommunityReactionSummaryEntry]),
            timestamp_seconds: T.nilable(::Integer),
            deleted: T.nilable(T::Boolean),
            is_own: T.nilable(T::Boolean)
          )
            .void
        }
        def initialize(
          created_at:,
          id:,
          post_id:,
          author:,
          content:,
          modified_at: nil,
          parent_id: nil,
          reactions: nil,
          timestamp_seconds: nil,
          deleted: false,
          is_own: false
        )
          @created_at = created_at
          @id = id
          @post_id = post_id
          @author = author
          @content = content
          @modified_at = modified_at
          @parent_id = parent_id
          @reactions = reactions
          @timestamp_seconds = timestamp_seconds
          @deleted = deleted
          @is_own = is_own
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @created_at == other.created_at
          return false unless @id == other.id
          return false unless @post_id == other.post_id
          return false unless @author == other.author
          return false unless @content == other.content
          return false unless @modified_at == other.modified_at
          return false unless @parent_id == other.parent_id
          return false unless @reactions == other.reactions
          return false unless @timestamp_seconds == other.timestamp_seconds
          return false unless @deleted == other.deleted
          return false unless @is_own == other.is_own
          true
        end
      end
    end
  end
end
