# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CommunityEventReadType
        include ::Crystalline::Enum
        enums do
          WORKSHOP = new("workshop")
          OFFICE = new("office")
          COHORT = new("cohort")
          GUEST = new("guest")
        end

        open!
      end
    end
  end
end
