# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Returned by the toggle endpoint so optimistic clients have a
      # server-confirmed state to settle on.
      #
      # `reactions` is the authoritative per-emoji breakdown for this
      # target after the toggle — clients should replace their cached
      # `reactions` array with this value rather than mutating it in
      # place. `count` is the sum of `reactions[].count` and matches
      # `community_posts.reaction_count` for post targets.
      class CommunityReactionToggleResult
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :emoji,
          Models::Components::CommunityReactionToggleResultEmoji,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("emoji"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(
                Models::Components::CommunityReactionToggleResultEmoji,
                false
              )
            }
          }
        )

        field(
          :active,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("active"), required: true}}
        )

        field(
          :count,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("count"), required: true}}
        )

        field(
          :reactions,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::CommunityReactionSummaryEntry)),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("reactions")}}
        )

        sig {
          params(
            emoji: Models::Components::CommunityReactionToggleResultEmoji,
            active: T::Boolean,
            count: ::Integer,
            reactions: T.nilable(T::Array[Models::Components::CommunityReactionSummaryEntry])
          )
            .void
        }
        def initialize(emoji:, active:, count:, reactions: nil)
          @emoji = emoji
          @active = active
          @count = count
          @reactions = reactions
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @emoji == other.emoji
          return false unless @active == other.active
          return false unless @count == other.count
          return false unless @reactions == other.reactions
          true
        end
      end
    end
  end
end
