# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # One row in the customer-portal picker. `community_enabled` is
      # false when the creator hasn't enabled the feed for this course yet
      # (or the settings row doesn't exist at all).
      class CommunityCourseSummary
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :course_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("course_id"), required: true}}
        )

        field(
          :community_enabled,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("community_enabled"), required: true}}
        )

        field(
          :course_title,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("course_title"), required: true}}
        )

        field(
          :course_thumbnail_url,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("course_thumbnail_url"), required: true}}
        )

        field(
          :course_thumbnail_object_position,
          Crystalline::Nilable.new(::String),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("course_thumbnail_object_position"),
              required: true
            }
          }
        )

        sig {
          params(
            course_id: ::String,
            community_enabled: T::Boolean,
            course_title: T.nilable(::String),
            course_thumbnail_url: T.nilable(::String),
            course_thumbnail_object_position: T.nilable(::String)
          )
            .void
        }
        def initialize(
          course_id:,
          community_enabled:,
          course_title: nil,
          course_thumbnail_url: nil,
          course_thumbnail_object_position: nil
        )
          @course_id = course_id
          @community_enabled = community_enabled
          @course_title = course_title
          @course_thumbnail_url = course_thumbnail_url
          @course_thumbnail_object_position = course_thumbnail_object_position
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @course_id == other.course_id
          return false unless @community_enabled == other.community_enabled
          return false unless @course_title == other.course_title
          return false unless @course_thumbnail_url == other.course_thumbnail_url
          return false unless @course_thumbnail_object_position == other.course_thumbnail_object_position
          true
        end
      end
    end
  end
end
