# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # CommunityPostSortProperty - Feed sort options surfaced as the left-rail "Sort" list. Not a
      # free-form column sort — these are pre-baked queries the repository
      # knows how to apply.
      class CommunityPostSortProperty < T::Enum
        enums do
          RECENT = new("recent")
          TOP_WEEK = new("top_week")
          UNANSWERED = new("unanswered")
        end
      end
    end
  end
end
