# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CommunityPostCreateBodyFormat < T::Enum
        enums do
          MARKDOWN = new("markdown")
          PLAIN = new("plain")
        end
      end
    end
  end
end
