# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CommunityPostReadType
        include ::Crystalline::Enum
        enums do
          TEXT = new("text")
          VIDEO = new("video")
        end

        open!
      end
    end
  end
end
