# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Module-only chip used on activity pins where the activity is
      # scoped to a module (no lesson). Mirrors CommunityLessonChip's shape
      # so the FE can render the same pill component.
      class CommunityModuleChip
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :module_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("module_id"), required: true}}
        )

        field(
          :module_title,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("module_title")}}
        )

        sig { params(module_id: ::String, module_title: T.nilable(::String)).void }
        def initialize(module_id:, module_title: nil)
          @module_id = module_id
          @module_title = module_title
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @module_id == other.module_id
          return false unless @module_title == other.module_title
          true
        end
      end
    end
  end
end
