# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CostMetadataOutput
        extend T::Sig
        include Crystalline::MetadataFields

        # The amount in cents.
        field(
          :amount,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("amount"), required: true}}
        )
        # The currency. Currently, only `usd` is supported.
        field(
          :currency,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("currency"), required: true}}
        )

        sig { params(amount: ::String, currency: ::String).void }
        def initialize(amount:, currency:)
          @amount = amount
          @currency = currency
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @amount == other.amount
          return false unless @currency == other.currency
          true
        end
      end
    end
  end
end
