# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CountAggregation
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :func,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("func")}}
        )

        sig { params(func: T.nilable(::String)).void }
        def initialize(func: "count")
          unless func == "count"
            raise ArgumentError, "Invalid value for func"
          end

          @func = "count"
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @func == other.func
          true
        end
      end
    end
  end
end
