# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CourseProgressRead
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :total_lessons,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("total_lessons"), required: true}}
        )

        field(
          :completed_lessons,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("completed_lessons"), required: true}}
        )

        field(
          :completion_percent,
          ::Float,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("completion_percent"), required: true}}
        )

        field(
          :completed,
          Crystalline::Hash.new(Symbol, ::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("completed"), required: true}}
        )

        sig {
          params(
            total_lessons: ::Integer,
            completed_lessons: ::Integer,
            completion_percent: ::Float,
            completed: T::Hash[Symbol, ::String]
          )
            .void
        }
        def initialize(total_lessons:, completed_lessons:, completion_percent:, completed:)
          @total_lessons = total_lessons
          @completed_lessons = completed_lessons
          @completion_percent = completion_percent
          @completed = completed
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @total_lessons == other.total_lessons
          return false unless @completed_lessons == other.completed_lessons
          return false unless @completion_percent == other.completion_percent
          return false unless @completed == other.completed
          true
        end
      end
    end
  end
end
