# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CustomerPortalUsageSettings
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :show,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("show"), required: true}}
        )

        sig { params(show: T::Boolean).void }
        def initialize(show:)
          @show = show
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @show == other.show
          true
        end
      end
    end
  end
end
