# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CustomerNotificationPreferencesRead
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :email_enabled,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("email_enabled"), required: true}}
        )

        field(
          :bell_enabled,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("bell_enabled")}}
        )

        sig { params(email_enabled: T::Boolean, bell_enabled: T.nilable(T::Boolean)).void }
        def initialize(email_enabled:, bell_enabled: true)
          @email_enabled = email_enabled
          @bell_enabled = bell_enabled
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @email_enabled == other.email_enabled
          return false unless @bell_enabled == other.bell_enabled
          true
        end
      end
    end
  end
end
