# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CustomerSeat
        extend T::Sig
        include Crystalline::MetadataFields

        # Creation timestamp of the object.
        field(
          :created_at,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("created_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # The seat ID
        field :id, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("id"), required: true}}

        field(
          :status,
          Models::Components::SeatStatus,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("status"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::SeatStatus, false)
            }
          }
        )
        # Last modification timestamp of the object.
        field(
          :modified_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("modified_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # The subscription ID (for recurring seats)
        field(
          :subscription_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("subscription_id")}}
        )
        # The order ID (for one-time purchase seats)
        field(
          :order_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("order_id")}}
        )
        # The customer ID. When member_model_enabled is true, this is the billing customer (purchaser). When false, this is the seat member customer.
        field(
          :customer_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("customer_id")}}
        )
        # The member ID of the seat occupant
        field(
          :member_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("member_id")}}
        )
        # The member associated with this seat
        field(
          :member,
          Crystalline::Nilable.new(Models::Components::Member),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("member")}}
        )
        # Email of the seat member (set when member_model_enabled is true)
        field(
          :email,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("email")}}
        )
        # The assigned customer email
        field(
          :customer_email,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("customer_email")}}
        )
        # When the invitation token expires
        field(
          :invitation_token_expires_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("invitation_token_expires_at"),
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(true)
            }
          }
        )
        # When the seat was claimed
        field(
          :claimed_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("claimed_at"),
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(true)
            }
          }
        )
        # When the seat was revoked
        field(
          :revoked_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("revoked_at"),
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(true)
            }
          }
        )
        # Additional metadata for the seat
        field(
          :seat_metadata,
          Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("seat_metadata")}}
        )

        sig {
          params(
            created_at: ::DateTime,
            id: ::String,
            status: Models::Components::SeatStatus,
            modified_at: T.nilable(::DateTime),
            subscription_id: T.nilable(::String),
            order_id: T.nilable(::String),
            customer_id: T.nilable(::String),
            member_id: T.nilable(::String),
            member: T.nilable(Models::Components::Member),
            email: T.nilable(::String),
            customer_email: T.nilable(::String),
            invitation_token_expires_at: T.nilable(::DateTime),
            claimed_at: T.nilable(::DateTime),
            revoked_at: T.nilable(::DateTime),
            seat_metadata: T.nilable(T::Hash[Symbol, ::Object])
          )
            .void
        }
        def initialize(
          created_at:,
          id:,
          status:,
          modified_at: nil,
          subscription_id: nil,
          order_id: nil,
          customer_id: nil,
          member_id: nil,
          member: nil,
          email: nil,
          customer_email: nil,
          invitation_token_expires_at: nil,
          claimed_at: nil,
          revoked_at: nil,
          seat_metadata: nil
        )
          @created_at = created_at
          @id = id
          @status = status
          @modified_at = modified_at
          @subscription_id = subscription_id
          @order_id = order_id
          @customer_id = customer_id
          @member_id = member_id
          @member = member
          @email = email
          @customer_email = customer_email
          @invitation_token_expires_at = invitation_token_expires_at
          @claimed_at = claimed_at
          @revoked_at = revoked_at
          @seat_metadata = seat_metadata
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @created_at == other.created_at
          return false unless @id == other.id
          return false unless @status == other.status
          return false unless @modified_at == other.modified_at
          return false unless @subscription_id == other.subscription_id
          return false unless @order_id == other.order_id
          return false unless @customer_id == other.customer_id
          return false unless @member_id == other.member_id
          return false unless @member == other.member
          return false unless @email == other.email
          return false unless @customer_email == other.customer_email
          return false unless @invitation_token_expires_at == other.invitation_token_expires_at
          return false unless @claimed_at == other.claimed_at
          return false unless @revoked_at == other.revoked_at
          return false unless @seat_metadata == other.seat_metadata
          true
        end
      end
    end
  end
end
