# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Schema to update an order.
      class CustomerOrderUpdate
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the customer that should appear on the invoice.
        field(
          :billing_name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("billing_name")}}
        )
        # The address of the customer that should appear on the invoice. Country and state fields cannot be updated.
        field(
          :billing_address,
          Crystalline::Nilable.new(Models::Components::AddressInput),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("billing_address")}}
        )

        sig {
          params(billing_name: T.nilable(::String), billing_address: T.nilable(Models::Components::AddressInput)).void
        }
        def initialize(billing_name: nil, billing_address: nil)
          @billing_name = billing_name
          @billing_address = billing_address
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @billing_name == other.billing_name
          return false unless @billing_address == other.billing_address
          true
        end
      end
    end
  end
end
