# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CustomerUpdate
        extend T::Sig
        include Crystalline::MetadataFields

        # Key-value object allowing you to store additional information.
        #
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        #
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        #
        # You can store up to **50 key-value pairs**.
        field(
          :metadata,
          Crystalline::Nilable.new(
            Crystalline::Hash.new(
              Symbol,
              Crystalline::Union.new(::String, ::Integer, ::Float, Crystalline::Boolean.new)
            )
          ),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("metadata")}}
        )
        # The email address of the customer. This must be unique within the organization.
        field(
          :email,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("email")}}
        )

        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("name")}}
        )

        field(
          :billing_address,
          Crystalline::Nilable.new(Models::Components::AddressInput),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("billing_address")}}
        )

        field(
          :tax_id,
          Crystalline::Nilable.new(
            Crystalline::Array.new(Crystalline::Union.new(::String, Models::Components::TaxIDFormat))
          ),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("tax_id")}}
        )
        # The ID of the customer in your system. This must be unique within the organization. Once set, it can't be updated.
        field(
          :external_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("external_id")}}
        )
        # The customer type. Can only be upgraded from 'individual' to 'team', never downgraded.
        field(
          :type,
          Crystalline::Nilable.new(Models::Components::CustomerType),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("type"),
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::CustomerType, true)
            }
          }
        )

        sig {
          params(
            metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]),
            email: T.nilable(::String),
            name: T.nilable(::String),
            billing_address: T.nilable(Models::Components::AddressInput),
            tax_id: T.nilable(T::Array[T.any(::String, Models::Components::TaxIDFormat)]),
            external_id: T.nilable(::String),
            type: T.nilable(Models::Components::CustomerType)
          )
            .void
        }
        def initialize(
          metadata: nil,
          email: nil,
          name: nil,
          billing_address: nil,
          tax_id: nil,
          external_id: nil,
          type: nil
        )
          @metadata = metadata
          @email = email
          @name = name
          @billing_address = billing_address
          @tax_id = tax_id
          @external_id = external_id
          @type = type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @metadata == other.metadata
          return false unless @email == other.email
          return false unless @name == other.name
          return false unless @billing_address == other.billing_address
          return false unless @tax_id == other.tax_id
          return false unless @external_id == other.external_id
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
