# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CustomerWalletSortProperty < T::Enum
        enums do
          CREATED_AT = new("created_at")
          MINUS_CREATED_AT = new("-created_at")
          BALANCE = new("balance")
          MINUS_BALANCE = new("-balance")
        end
      end
    end
  end
end
