# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CustomerPaymentMethodCreateRequiresActionResponse
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :client_secret,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("client_secret"), required: true}}
        )

        field(
          :status,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("status"), required: true}}
        )

        sig { params(client_secret: ::String, status: ::String).void }
        def initialize(client_secret:, status: "requires_action")
          @client_secret = client_secret
          unless status == "requires_action"
            raise ArgumentError, "Invalid value for status"
          end

          @status = "requires_action"
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @client_secret == other.client_secret
          return false unless @status == other.status
          true
        end
      end
    end
  end
end
