# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Response after successfully claiming a seat.
      class CustomerSeatClaimResponse
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :seat,
          Models::Components::CustomerSeat,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("seat"), required: true}}
        )
        # Session token for immediate customer portal access
        field(
          :customer_session_token,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("customer_session_token"), required: true}}
        )

        sig { params(seat: Models::Components::CustomerSeat, customer_session_token: ::String).void }
        def initialize(seat:, customer_session_token:)
          @seat = seat
          @customer_session_token = customer_session_token
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @seat == other.seat
          return false unless @customer_session_token == other.customer_session_token
          true
        end
      end
    end
  end
end
