# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CustomerUpdatedMetadata
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :customer_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("customer_id"), required: true}}
        )

        field(
          :customer_email,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("customer_email"), required: true}}
        )

        field(
          :updated_fields,
          Models::Components::CustomerUpdatedFields,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("updated_fields"), required: true}}
        )

        field(
          :customer_name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("customer_name"), required: true}}
        )

        field(
          :customer_external_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("customer_external_id"), required: true}}
        )

        sig {
          params(
            customer_id: ::String,
            customer_email: ::String,
            updated_fields: Models::Components::CustomerUpdatedFields,
            customer_name: T.nilable(::String),
            customer_external_id: T.nilable(::String)
          )
            .void
        }
        def initialize(customer_id:, customer_email:, updated_fields:, customer_name: nil, customer_external_id: nil)
          @customer_id = customer_id
          @customer_email = customer_email
          @updated_fields = updated_fields
          @customer_name = customer_name
          @customer_external_id = customer_external_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @customer_id == other.customer_id
          return false unless @customer_email == other.customer_email
          return false unless @updated_fields == other.updated_fields
          return false unless @customer_name == other.customer_name
          return false unless @customer_external_id == other.customer_external_id
          true
        end
      end
    end
  end
end
