# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CustomerCustomerSession
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :expires_at,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("expires_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        field(
          :return_url,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("return_url"), required: true}}
        )

        sig { params(expires_at: ::DateTime, return_url: T.nilable(::String)).void }
        def initialize(expires_at:, return_url: nil)
          @expires_at = expires_at
          @return_url = return_url
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @expires_at == other.expires_at
          return false unless @return_url == other.return_url
          true
        end
      end
    end
  end
end
