# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class CustomerUpdatedFields
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("name")}}
        )

        field(
          :email,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("email")}}
        )

        field(
          :billing_address,
          Crystalline::Nilable.new(Models::Components::AddressDict),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("billing_address")}}
        )

        field(
          :tax_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("tax_id")}}
        )

        field(
          :metadata,
          Crystalline::Nilable.new(
            Crystalline::Hash.new(Symbol, Crystalline::Union.new(::String, ::Integer, Crystalline::Boolean.new))
          ),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("metadata")}}
        )

        sig {
          params(
            name: T.nilable(::String),
            email: T.nilable(::String),
            billing_address: T.nilable(Models::Components::AddressDict),
            tax_id: T.nilable(::String),
            metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, T::Boolean)])
          )
            .void
        }
        def initialize(name: nil, email: nil, billing_address: nil, tax_id: nil, metadata: nil)
          @name = name
          @email = email
          @billing_address = billing_address
          @tax_id = tax_id
          @metadata = metadata
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @name == other.name
          return false unless @email == other.email
          return false unless @billing_address == other.billing_address
          return false unless @tax_id == other.tax_id
          return false unless @metadata == other.metadata
          true
        end
      end
    end
  end
end
