# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class DiscountPercentageOnceForeverDurationBase
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :duration,
          Models::Components::DiscountDuration,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("duration"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::DiscountDuration, false)
            }
          }
        )

        field(
          :type,
          Models::Components::DiscountType,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("type"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::DiscountType, false)
            }
          }
        )
        # Discount percentage in basis points. A basis point is 1/100th of a percent. For example, 1000 basis points equals a 10% discount.
        field(
          :basis_points,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("basis_points"), required: true}}
        )
        # Creation timestamp of the object.
        field(
          :created_at,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("created_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # The ID of the object.
        field :id, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("id"), required: true}}

        field(
          :metadata,
          Crystalline::Hash.new(Symbol, Crystalline::Union.new(::String, ::Integer, ::Float, Crystalline::Boolean.new)),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("metadata"), required: true}}
        )
        # Name of the discount. Will be displayed to the customer when the discount is applied.
        field :name, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("name"), required: true}}
        # Number of times the discount has been redeemed.
        field(
          :redemptions_count,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("redemptions_count"), required: true}}
        )
        # The organization ID.
        field(
          :organization_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("organization_id"), required: true}}
        )
        # Last modification timestamp of the object.
        field(
          :modified_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("modified_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # Code customers can use to apply the discount during checkout.
        field(
          :code,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("code"), required: true}}
        )
        # Timestamp after which the discount is redeemable.
        field(
          :starts_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("starts_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # Timestamp after which the discount is no longer redeemable.
        field(
          :ends_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("ends_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # Maximum number of times the discount can be redeemed.
        field(
          :max_redemptions,
          Crystalline::Nilable.new(::Integer),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("max_redemptions"), required: true}}
        )

        sig {
          params(
            duration: Models::Components::DiscountDuration,
            type: Models::Components::DiscountType,
            basis_points: ::Integer,
            created_at: ::DateTime,
            id: ::String,
            metadata: T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)],
            name: ::String,
            redemptions_count: ::Integer,
            organization_id: ::String,
            modified_at: T.nilable(::DateTime),
            code: T.nilable(::String),
            starts_at: T.nilable(::DateTime),
            ends_at: T.nilable(::DateTime),
            max_redemptions: T.nilable(::Integer)
          )
            .void
        }
        def initialize(
          duration:,
          type:,
          basis_points:,
          created_at:,
          id:,
          metadata:,
          name:,
          redemptions_count:,
          organization_id:,
          modified_at: nil,
          code: nil,
          starts_at: nil,
          ends_at: nil,
          max_redemptions: nil
        )
          @duration = duration
          @type = type
          @basis_points = basis_points
          @created_at = created_at
          @id = id
          @metadata = metadata
          @name = name
          @redemptions_count = redemptions_count
          @organization_id = organization_id
          @modified_at = modified_at
          @code = code
          @starts_at = starts_at
          @ends_at = ends_at
          @max_redemptions = max_redemptions
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @duration == other.duration
          return false unless @type == other.type
          return false unless @basis_points == other.basis_points
          return false unless @created_at == other.created_at
          return false unless @id == other.id
          return false unless @metadata == other.metadata
          return false unless @name == other.name
          return false unless @redemptions_count == other.redemptions_count
          return false unless @organization_id == other.organization_id
          return false unless @modified_at == other.modified_at
          return false unless @code == other.code
          return false unless @starts_at == other.starts_at
          return false unless @ends_at == other.ends_at
          return false unless @max_redemptions == other.max_redemptions
          true
        end
      end
    end
  end
end
