# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Schema to create a fixed amount discount that is applied once or forever.
      class DiscountFixedOnceForeverDurationCreate
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :duration,
          Models::Components::DiscountDuration,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("duration"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::DiscountDuration, false)
            }
          }
        )

        field(
          :type,
          Models::Components::DiscountType,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("type"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::DiscountType, false)
            }
          }
        )
        # Fixed amount to discount from the invoice total.
        field(
          :amount,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("amount"), required: true}}
        )
        # Name of the discount. Will be displayed to the customer when the discount is applied.
        field :name, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("name"), required: true}}
        # Key-value object allowing you to store additional information.
        #
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        #
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        #
        # You can store up to **50 key-value pairs**.
        field(
          :metadata,
          Crystalline::Nilable.new(
            Crystalline::Hash.new(
              Symbol,
              Crystalline::Union.new(::String, ::Integer, ::Float, Crystalline::Boolean.new)
            )
          ),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("metadata")}}
        )
        # The currency. Currently, only `usd` is supported.
        field(
          :currency,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("currency")}}
        )
        # Code customers can use to apply the discount during checkout. Must be between 3 and 256 characters long and contain only alphanumeric characters.If not provided, the discount can only be applied via the API.
        field(
          :code,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("code")}}
        )
        # Optional timestamp after which the discount is redeemable.
        field(
          :starts_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("starts_at"),
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(true)
            }
          }
        )
        # Optional timestamp after which the discount is no longer redeemable.
        field(
          :ends_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("ends_at"),
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(true)
            }
          }
        )
        # Optional maximum number of times the discount can be redeemed.
        field(
          :max_redemptions,
          Crystalline::Nilable.new(::Integer),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("max_redemptions")}}
        )

        field(
          :products,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("products")}}
        )
        # The ID of the organization owning the discount. **Required unless you use an organization token.**
        field(
          :organization_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("organization_id")}}
        )

        sig {
          params(
            duration: Models::Components::DiscountDuration,
            type: Models::Components::DiscountType,
            amount: ::Integer,
            name: ::String,
            metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]),
            currency: T.nilable(::String),
            code: T.nilable(::String),
            starts_at: T.nilable(::DateTime),
            ends_at: T.nilable(::DateTime),
            max_redemptions: T.nilable(::Integer),
            products: T.nilable(T::Array[::String]),
            organization_id: T.nilable(::String)
          )
            .void
        }
        def initialize(
          duration:,
          type:,
          amount:,
          name:,
          metadata: nil,
          currency: "usd",
          code: nil,
          starts_at: nil,
          ends_at: nil,
          max_redemptions: nil,
          products: nil,
          organization_id: nil
        )
          @duration = duration
          @type = type
          @amount = amount
          @name = name
          @metadata = metadata
          @currency = currency
          @code = code
          @starts_at = starts_at
          @ends_at = ends_at
          @max_redemptions = max_redemptions
          @products = products
          @organization_id = organization_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @duration == other.duration
          return false unless @type == other.type
          return false unless @amount == other.amount
          return false unless @name == other.name
          return false unless @metadata == other.metadata
          return false unless @currency == other.currency
          return false unless @code == other.code
          return false unless @starts_at == other.starts_at
          return false unless @ends_at == other.ends_at
          return false unless @max_redemptions == other.max_redemptions
          return false unless @products == other.products
          return false unless @organization_id == other.organization_id
          true
        end
      end
    end
  end
end
