# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Schema representing a dispute.
      #
      # A dispute is a challenge raised by a customer or their bank regarding a payment.
      class Dispute
        extend T::Sig
        include Crystalline::MetadataFields

        # Creation timestamp of the object.
        field(
          :created_at,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("created_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # The ID of the object.
        field :id, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("id"), required: true}}

        field(
          :status,
          Models::Components::DisputeStatus,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("status"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::DisputeStatus, false)
            }
          }
        )
        # Whether the dispute has been resolved (won or lost).
        field(
          :resolved,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("resolved"), required: true}}
        )
        # Whether the dispute is closed (prevented, won, or lost).
        field(
          :closed,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("closed"), required: true}}
        )
        # Amount in cents disputed.
        field(
          :amount,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("amount"), required: true}}
        )
        # Tax amount in cents disputed.
        field(
          :tax_amount,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("tax_amount"), required: true}}
        )
        # Currency code of the dispute.
        field(
          :currency,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("currency"), required: true}}
        )
        # The ID of the order associated with the dispute.
        field(
          :order_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("order_id"), required: true}}
        )
        # The ID of the payment associated with the dispute.
        field(
          :payment_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("payment_id"), required: true}}
        )
        # Last modification timestamp of the object.
        field(
          :modified_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("modified_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        sig {
          params(
            created_at: ::DateTime,
            id: ::String,
            status: Models::Components::DisputeStatus,
            resolved: T::Boolean,
            closed: T::Boolean,
            amount: ::Integer,
            tax_amount: ::Integer,
            currency: ::String,
            order_id: ::String,
            payment_id: ::String,
            modified_at: T.nilable(::DateTime)
          )
            .void
        }
        def initialize(
          created_at:,
          id:,
          status:,
          resolved:,
          closed:,
          amount:,
          tax_amount:,
          currency:,
          order_id:,
          payment_id:,
          modified_at: nil
        )
          @created_at = created_at
          @id = id
          @status = status
          @resolved = resolved
          @closed = closed
          @amount = amount
          @tax_amount = tax_amount
          @currency = currency
          @order_id = order_id
          @payment_id = payment_id
          @modified_at = modified_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @created_at == other.created_at
          return false unless @id == other.id
          return false unless @status == other.status
          return false unless @resolved == other.resolved
          return false unless @closed == other.closed
          return false unless @amount == other.amount
          return false unless @tax_amount == other.tax_amount
          return false unless @currency == other.currency
          return false unless @order_id == other.order_id
          return false unless @payment_id == other.payment_id
          return false unless @modified_at == other.modified_at
          true
        end
      end
    end
  end
end
