# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class EventName
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the event.
        field :name, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("name"), required: true}}

        field(
          :source,
          Models::Components::EventSource,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("source"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::EventSource, false)
            }
          }
        )
        # Number of times the event has occurred.
        field(
          :occurrences,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("occurrences"), required: true}}
        )
        # The first time the event occurred.
        field(
          :first_seen,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("first_seen"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # The last time the event occurred.
        field(
          :last_seen,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("last_seen"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        sig {
          params(
            name: ::String,
            source: Models::Components::EventSource,
            occurrences: ::Integer,
            first_seen: ::DateTime,
            last_seen: ::DateTime
          )
            .void
        }
        def initialize(name:, source:, occurrences:, first_seen:, last_seen:)
          @name = name
          @source = source
          @occurrences = occurrences
          @first_seen = first_seen
          @last_seen = last_seen
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @name == other.name
          return false unless @source == other.source
          return false unless @occurrences == other.occurrences
          return false unless @first_seen == other.first_seen
          return false unless @last_seen == other.last_seen
          true
        end
      end
    end
  end
end
