# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class EventsIngestResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # Number of events inserted.
        field(
          :inserted,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("inserted"), required: true}}
        )
        # Number of duplicate events skipped.
        field(
          :duplicates,
          Crystalline::Nilable.new(::Integer),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("duplicates")}}
        )

        sig { params(inserted: ::Integer, duplicates: T.nilable(::Integer)).void }
        def initialize(inserted:, duplicates: 0)
          @inserted = inserted
          @duplicates = duplicates
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @inserted == other.inserted
          return false unless @duplicates == other.duplicates
          true
        end
      end
    end
  end
end
