# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class FileUpload
        extend T::Sig
        include Crystalline::MetadataFields

        # The ID of the object.
        field :id, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("id"), required: true}}

        field(
          :organization_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("organization_id"), required: true}}
        )

        field :name, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("name"), required: true}}

        field :path, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("path"), required: true}}

        field(
          :mime_type,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("mime_type"), required: true}}
        )

        field :size, ::Integer, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("size"), required: true}}

        field(
          :upload,
          Models::Components::S3FileUploadMultipart,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("upload"), required: true}}
        )

        field(
          :service,
          Models::Components::FileServiceTypes,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("service"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::FileServiceTypes, false)
            }
          }
        )

        field(
          :size_readable,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("size_readable"), required: true}}
        )

        field(
          :storage_version,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("storage_version"), required: true}}
        )

        field(
          :checksum_etag,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("checksum_etag"), required: true}}
        )

        field(
          :checksum_sha256_base64,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("checksum_sha256_base64"), required: true}}
        )

        field(
          :checksum_sha256_hex,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("checksum_sha256_hex"), required: true}}
        )

        field(
          :last_modified_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("last_modified_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        field(
          :version,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("version"), required: true}}
        )

        field(
          :is_uploaded,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("is_uploaded")}}
        )

        sig {
          params(
            id: ::String,
            organization_id: ::String,
            name: ::String,
            path: ::String,
            mime_type: ::String,
            size: ::Integer,
            upload: Models::Components::S3FileUploadMultipart,
            service: Models::Components::FileServiceTypes,
            size_readable: ::String,
            storage_version: T.nilable(::String),
            checksum_etag: T.nilable(::String),
            checksum_sha256_base64: T.nilable(::String),
            checksum_sha256_hex: T.nilable(::String),
            last_modified_at: T.nilable(::DateTime),
            version: T.nilable(::String),
            is_uploaded: T.nilable(T::Boolean)
          )
            .void
        }
        def initialize(
          id:,
          organization_id:,
          name:,
          path:,
          mime_type:,
          size:,
          upload:,
          service:,
          size_readable:,
          storage_version: nil,
          checksum_etag: nil,
          checksum_sha256_base64: nil,
          checksum_sha256_hex: nil,
          last_modified_at: nil,
          version: nil,
          is_uploaded: false
        )
          @id = id
          @organization_id = organization_id
          @name = name
          @path = path
          @mime_type = mime_type
          @size = size
          @upload = upload
          @service = service
          @size_readable = size_readable
          @storage_version = storage_version
          @checksum_etag = checksum_etag
          @checksum_sha256_base64 = checksum_sha256_base64
          @checksum_sha256_hex = checksum_sha256_hex
          @last_modified_at = last_modified_at
          @version = version
          @is_uploaded = is_uploaded
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @id == other.id
          return false unless @organization_id == other.organization_id
          return false unless @name == other.name
          return false unless @path == other.path
          return false unless @mime_type == other.mime_type
          return false unless @size == other.size
          return false unless @upload == other.upload
          return false unless @service == other.service
          return false unless @size_readable == other.size_readable
          return false unless @storage_version == other.storage_version
          return false unless @checksum_etag == other.checksum_etag
          return false unless @checksum_sha256_base64 == other.checksum_sha256_base64
          return false unless @checksum_sha256_hex == other.checksum_sha256_hex
          return false unless @last_modified_at == other.last_modified_at
          return false unless @version == other.version
          return false unless @is_uploaded == other.is_uploaded
          true
        end
      end
    end
  end
end
