# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class FileServiceTypes
        include ::Crystalline::Enum
        enums do
          DOWNLOADABLE = new("downloadable")
          PRODUCT_MEDIA = new("product_media")
          ORGANIZATION_AVATAR = new("organization_avatar")
          STOREFRONT_HEADER = new("storefront_header")
          STOREFRONT_LINK = new("storefront_link")
          COMMUNITY_POST_IMAGE = new("community_post_image")
        end

        open!
      end
    end
  end
end
