# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class FilterClause
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :property,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("property"), required: true}}
        )

        field(
          :operator,
          Models::Components::FilterOperator,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("operator"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::FilterOperator, false)
            }
          }
        )

        field(
          :value,
          Crystalline::Union.new(::String, ::Integer, Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("value"), required: true}}
        )

        sig {
          params(
            property: ::String,
            operator: Models::Components::FilterOperator,
            value: T.any(::String, ::Integer, T::Boolean)
          )
            .void
        }
        def initialize(property:, operator:, value:)
          @property = property
          @operator = operator
          @value = value
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @property == other.property
          return false unless @operator == other.operator
          return false unless @value == other.value
          true
        end
      end
    end
  end
end
