# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # A free recurring price for a product, i.e. a subscription.
      #
      # **Deprecated**: The recurring interval should be set on the product itself.
      class LegacyRecurringProductPriceFree
        extend T::Sig
        include Crystalline::MetadataFields

        # Creation timestamp of the object.
        field(
          :created_at,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("created_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # The ID of the price.
        field :id, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("id"), required: true}}

        field(
          :source,
          Models::Components::ProductPriceSource,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("source"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::ProductPriceSource, false)
            }
          }
        )

        field(
          :price_currency,
          Models::Components::PresentmentCurrency,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("price_currency"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::PresentmentCurrency, false)
            }
          }
        )
        # Whether the price is archived and no longer available.
        field(
          :is_archived,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("is_archived"), required: true}}
        )
        # The ID of the product owning the price.
        field(
          :product_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("product_id"), required: true}}
        )

        field(
          :recurring_interval,
          Models::Components::SubscriptionRecurringInterval,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("recurring_interval"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(
                Models::Components::SubscriptionRecurringInterval,
                false
              )
            }
          }
        )
        # Last modification timestamp of the object.
        field(
          :modified_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("modified_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        field(
          :amount_type,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("amount_type"), required: true}}
        )
        # The tax behavior of the price. If null, it defaults to the organization's default tax behavior.
        field(
          :tax_behavior,
          Crystalline::Nilable.new(Models::Components::TaxBehaviorOption),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("tax_behavior"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::TaxBehaviorOption, false)
            }
          }
        )
        # The type of the price.
        field :type, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("type"), required: true}}

        field(
          :legacy,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("legacy"), required: true}}
        )

        sig {
          params(
            created_at: ::DateTime,
            id: ::String,
            source: Models::Components::ProductPriceSource,
            price_currency: Models::Components::PresentmentCurrency,
            is_archived: T::Boolean,
            product_id: ::String,
            recurring_interval: Models::Components::SubscriptionRecurringInterval,
            modified_at: T.nilable(::DateTime),
            amount_type: ::String,
            tax_behavior: T.nilable(Models::Components::TaxBehaviorOption),
            type: ::String,
            legacy: T::Boolean
          )
            .void
        }
        def initialize(
          created_at:,
          id:,
          source:,
          price_currency:,
          is_archived:,
          product_id:,
          recurring_interval:,
          modified_at: nil,
          amount_type: "free",
          tax_behavior: nil,
          type: "recurring",
          legacy: true
        )
          @created_at = created_at
          @id = id
          @source = source
          @price_currency = price_currency
          @is_archived = is_archived
          @product_id = product_id
          @recurring_interval = recurring_interval
          @modified_at = modified_at
          unless amount_type == "free"
            raise ArgumentError, "Invalid value for amount_type"
          end

          @amount_type = "free"
          @tax_behavior = tax_behavior
          unless type == "recurring"
            raise ArgumentError, "Invalid value for type"
          end

          @type = "recurring"
          unless legacy == true
            raise ArgumentError, "Invalid value for legacy"
          end

          @legacy = true
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @created_at == other.created_at
          return false unless @id == other.id
          return false unless @source == other.source
          return false unless @price_currency == other.price_currency
          return false unless @is_archived == other.is_archived
          return false unless @product_id == other.product_id
          return false unless @recurring_interval == other.recurring_interval
          return false unless @modified_at == other.modified_at
          return false unless @amount_type == other.amount_type
          return false unless @tax_behavior == other.tax_behavior
          return false unless @type == other.type
          return false unless @legacy == other.legacy
          true
        end
      end
    end
  end
end
