# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class LessonCommentAuthor
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :enrollment_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("enrollment_id"), required: true}}
        )

        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("name")}}
        )

        field(
          :avatar_url,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("avatar_url")}}
        )

        field(
          :is_instructor,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("is_instructor")}}
        )

        sig {
          params(
            enrollment_id: ::String,
            name: T.nilable(::String),
            avatar_url: T.nilable(::String),
            is_instructor: T.nilable(T::Boolean)
          )
            .void
        }
        def initialize(enrollment_id:, name: nil, avatar_url: nil, is_instructor: false)
          @enrollment_id = enrollment_id
          @name = name
          @avatar_url = avatar_url
          @is_instructor = is_instructor
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @enrollment_id == other.enrollment_id
          return false unless @name == other.name
          return false unless @avatar_url == other.avatar_url
          return false unless @is_instructor == other.is_instructor
          true
        end
      end
    end
  end
end
