# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class LessonCommentLikeRead
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :liked,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("liked"), required: true}}
        )

        field(
          :likes,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("likes"), required: true}}
        )

        sig { params(liked: T::Boolean, likes: ::Integer).void }
        def initialize(liked:, likes:)
          @liked = liked
          @likes = likes
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @liked == other.liked
          return false unless @likes == other.likes
          true
        end
      end
    end
  end
end
