# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class LessonCommentAuthor
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :enrollment_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("enrollment_id"), required: true}}
        )

        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("name")}}
        )

        sig { params(enrollment_id: ::String, name: T.nilable(::String)).void }
        def initialize(enrollment_id:, name: nil)
          @enrollment_id = enrollment_id
          @name = name
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @enrollment_id == other.enrollment_id
          return false unless @name == other.name
          true
        end
      end
    end
  end
end
