# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class LicenseKeyActivationBase
        extend T::Sig
        include Crystalline::MetadataFields

        field :id, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("id"), required: true}}

        field(
          :license_key_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("license_key_id"), required: true}}
        )

        field(
          :label,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("label"), required: true}}
        )

        field(
          :meta,
          Crystalline::Hash.new(Symbol, Crystalline::Union.new(::String, ::Integer, ::Float, Crystalline::Boolean.new)),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("meta"), required: true}}
        )

        field(
          :created_at,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("created_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        field(
          :modified_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("modified_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        sig {
          params(
            id: ::String,
            license_key_id: ::String,
            label: ::String,
            meta: T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)],
            created_at: ::DateTime,
            modified_at: T.nilable(::DateTime)
          )
            .void
        }
        def initialize(id:, license_key_id:, label:, meta:, created_at:, modified_at: nil)
          @id = id
          @license_key_id = license_key_id
          @label = label
          @meta = meta
          @created_at = created_at
          @modified_at = modified_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @id == other.id
          return false unless @license_key_id == other.license_key_id
          return false unless @label == other.label
          return false unless @meta == other.meta
          return false unless @created_at == other.created_at
          return false unless @modified_at == other.modified_at
          true
        end
      end
    end
  end
end
