# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class LicenseKeyActivate
        extend T::Sig
        include Crystalline::MetadataFields

        field :key, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("key"), required: true}}

        field(
          :organization_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("organization_id"), required: true}}
        )

        field(
          :label,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("label"), required: true}}
        )
        # Key-value object allowing you to set conditions that must match when validating the license key.
        #
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        #
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        #
        # You can store up to **50 key-value pairs**.
        field(
          :conditions,
          Crystalline::Nilable.new(
            Crystalline::Hash.new(
              Symbol,
              Crystalline::Union.new(::String, ::Integer, ::Float, Crystalline::Boolean.new)
            )
          ),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("conditions")}}
        )
        # Key-value object allowing you to store additional information about the activation
        #
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        #
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        #
        # You can store up to **50 key-value pairs**.
        field(
          :meta,
          Crystalline::Nilable.new(
            Crystalline::Hash.new(
              Symbol,
              Crystalline::Union.new(::String, ::Integer, ::Float, Crystalline::Boolean.new)
            )
          ),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("meta")}}
        )

        sig {
          params(
            key: ::String,
            organization_id: ::String,
            label: ::String,
            conditions: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)]),
            meta: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)])
          )
            .void
        }
        def initialize(key:, organization_id:, label:, conditions: nil, meta: nil)
          @key = key
          @organization_id = organization_id
          @label = label
          @conditions = conditions
          @meta = meta
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @key == other.key
          return false unless @organization_id == other.organization_id
          return false unless @label == other.label
          return false unless @conditions == other.conditions
          return false unless @meta == other.meta
          true
        end
      end
    end
  end
end
