# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # LinksPosition - DEPRECATED — use block_order. Where to show the links section relative to products. Kept so existing rows still validate.
      class LinksPosition
        include ::Crystalline::Enum
        enums do
          BEFORE_PRODUCTS = new("before_products")
          AFTER_PRODUCTS = new("after_products")
        end

        open!
      end
    end
  end
end
