# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class ListResource
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :items,
          Crystalline::Array.new(
            Crystalline::Union.new(Models::Components::CardPayment, Models::Components::GenericPayment)
          ),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("items"), required: true}}
        )

        field(
          :pagination,
          Models::Components::Pagination,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("pagination"), required: true}}
        )

        sig {
          params(
            items: T::Array[T.any(Models::Components::CardPayment, Models::Components::GenericPayment)],
            pagination: Models::Components::Pagination
          )
            .void
        }
        def initialize(items:, pagination:)
          @items = items
          @pagination = pagination
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @items == other.items
          return false unless @pagination == other.pagination
          true
        end
      end
    end
  end
end
