# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class MemberRole
        include ::Crystalline::Enum
        enums do
          OWNER = new("owner")
          BILLING_MANAGER = new("billing_manager")
          MEMBER = new("member")
        end

        open!
      end
    end
  end
end
