# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Schema for updating a member.
      class MemberUpdate
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("name")}}
        )
        # The role of the member within the customer.
        field(
          :role,
          Crystalline::Nilable.new(Models::Components::MemberRole),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("role"),
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::MemberRole, true)
            }
          }
        )

        sig { params(name: T.nilable(::String), role: T.nilable(Models::Components::MemberRole)).void }
        def initialize(name: nil, role: nil)
          @name = name
          @role = role
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @name == other.name
          return false unless @role == other.role
          true
        end
      end
    end
  end
end
