# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class MeterQuantities
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :quantities,
          Crystalline::Array.new(Models::Components::MeterQuantity),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("quantities"), required: true}}
        )
        # The total quantity for the period.
        field :total, ::Float, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("total"), required: true}}

        sig { params(quantities: T::Array[Models::Components::MeterQuantity], total: ::Float).void }
        def initialize(quantities:, total:)
          @quantities = quantities
          @total = total
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @quantities == other.quantities
          return false unless @total == other.total
          true
        end
      end
    end
  end
end
