# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class OAuth2ClientConfiguration
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :redirect_uris,
          Crystalline::Array.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("redirect_uris"), required: true}}
        )

        field(
          :client_name,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("client_name"), required: true}}
        )

        field(
          :grant_types,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::GrantTypes)),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("grant_types")}}
        )

        field(
          :response_types,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("response_types")}}
        )

        field(
          :default_sub_type,
          Crystalline::Nilable.new(Models::Components::SubType),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("default_sub_type"),
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::SubType, true)
            }
          }
        )

        field(
          :token_endpoint_auth_method,
          Crystalline::Nilable.new(Models::Components::TokenEndpointAuthMethod),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("token_endpoint_auth_method"),
              'decoder': ::OpenApiSDK::Utils.enum_from_string(Models::Components::TokenEndpointAuthMethod, true)
            }
          }
        )

        field(
          :scope,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("scope")}}
        )

        field(
          :client_uri,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("client_uri")}}
        )

        field(
          :logo_uri,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("logo_uri")}}
        )

        field(
          :tos_uri,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("tos_uri")}}
        )

        field(
          :policy_uri,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("policy_uri")}}
        )

        sig {
          params(
            redirect_uris: T::Array[::String],
            client_name: ::String,
            grant_types: T.nilable(T::Array[Models::Components::GrantTypes]),
            response_types: T.nilable(T::Array[::String]),
            default_sub_type: T.nilable(Models::Components::SubType),
            token_endpoint_auth_method: T.nilable(Models::Components::TokenEndpointAuthMethod),
            scope: T.nilable(::String),
            client_uri: T.nilable(::String),
            logo_uri: T.nilable(::String),
            tos_uri: T.nilable(::String),
            policy_uri: T.nilable(::String)
          )
            .void
        }
        def initialize(
          redirect_uris:,
          client_name:,
          grant_types: nil,
          response_types: nil,
          default_sub_type: nil,
          token_endpoint_auth_method: Models::Components::TokenEndpointAuthMethod::CLIENT_SECRET_POST,
          scope: "openid profile email user:read user:write organizations:read organizations:write custom_fields:read custom_fields:write discounts:read discounts:write checkout_links:read checkout_links:write checkouts:read checkouts:write transactions:read transactions:write payouts:read payouts:write products:read products:write benefits:read benefits:write events:read events:write meters:read meters:write files:read files:write subscriptions:read subscriptions:write customers:read customers:write members:read members:write wallets:read wallets:write disputes:read customer_meters:read customer_sessions:write member_sessions:write customer_seats:read customer_seats:write orders:read orders:write client_invoices:read client_invoices:write refunds:read refunds:write payments:read metrics:read webhooks:read webhooks:write license_keys:read license_keys:write customer_portal:read customer_portal:write notifications:read notifications:write notification_recipients:read notification_recipients:write organization_access_tokens:read organization_access_tokens:write",
          client_uri: nil,
          logo_uri: nil,
          tos_uri: nil,
          policy_uri: nil
        )
          @redirect_uris = redirect_uris
          @client_name = client_name
          @grant_types = grant_types
          @response_types = response_types
          @default_sub_type = default_sub_type
          @token_endpoint_auth_method = token_endpoint_auth_method
          @scope = scope
          @client_uri = client_uri
          @logo_uri = logo_uri
          @tos_uri = tos_uri
          @policy_uri = policy_uri
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @redirect_uris == other.redirect_uris
          return false unless @client_name == other.client_name
          return false unless @grant_types == other.grant_types
          return false unless @response_types == other.response_types
          return false unless @default_sub_type == other.default_sub_type
          return false unless @token_endpoint_auth_method == other.token_endpoint_auth_method
          return false unless @scope == other.scope
          return false unless @client_uri == other.client_uri
          return false unless @logo_uri == other.logo_uri
          return false unless @tos_uri == other.tos_uri
          return false unless @policy_uri == other.policy_uri
          true
        end
      end
    end
  end
end
