# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class OAuth2ClientPublic
        extend T::Sig
        include Crystalline::MetadataFields

        # Creation timestamp of the object.
        field(
          :created_at,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("created_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        field(
          :client_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("client_id"), required: true}}
        )
        # Last modification timestamp of the object.
        field(
          :modified_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("modified_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        field(
          :client_name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("client_name"), required: true}}
        )

        field(
          :client_uri,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("client_uri"), required: true}}
        )

        field(
          :logo_uri,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("logo_uri"), required: true}}
        )

        field(
          :tos_uri,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("tos_uri"), required: true}}
        )

        field(
          :policy_uri,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("policy_uri"), required: true}}
        )

        sig {
          params(
            created_at: ::DateTime,
            client_id: ::String,
            modified_at: T.nilable(::DateTime),
            client_name: T.nilable(::String),
            client_uri: T.nilable(::String),
            logo_uri: T.nilable(::String),
            tos_uri: T.nilable(::String),
            policy_uri: T.nilable(::String)
          )
            .void
        }
        def initialize(
          created_at:,
          client_id:,
          modified_at: nil,
          client_name: nil,
          client_uri: nil,
          logo_uri: nil,
          tos_uri: nil,
          policy_uri: nil
        )
          @created_at = created_at
          @client_id = client_id
          @modified_at = modified_at
          @client_name = client_name
          @client_uri = client_uri
          @logo_uri = logo_uri
          @tos_uri = tos_uri
          @policy_uri = policy_uri
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @created_at == other.created_at
          return false unless @client_id == other.client_id
          return false unless @modified_at == other.modified_at
          return false unless @client_name == other.client_name
          return false unless @client_uri == other.client_uri
          return false unless @logo_uri == other.logo_uri
          return false unless @tos_uri == other.tos_uri
          return false unless @policy_uri == other.policy_uri
          true
        end
      end
    end
  end
end
