# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class OrderProduct
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :metadata,
          Crystalline::Hash.new(Symbol, Crystalline::Union.new(::String, ::Integer, ::Float, Crystalline::Boolean.new)),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("metadata"), required: true}}
        )
        # The ID of the object.
        field :id, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("id"), required: true}}
        # Creation timestamp of the object.
        field(
          :created_at,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("created_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # The name of the product.
        field :name, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("name"), required: true}}

        field(
          :visibility,
          Models::Components::ProductVisibility,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("visibility"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::ProductVisibility, false)
            }
          }
        )
        # Whether the product is a subscription.
        field(
          :is_recurring,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("is_recurring"), required: true}}
        )
        # Whether the product is archived and no longer available.
        field(
          :is_archived,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("is_archived"), required: true}}
        )
        # The ID of the organization owning the product.
        field(
          :organization_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("organization_id"), required: true}}
        )
        # Last modification timestamp of the object.
        field(
          :modified_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("modified_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # The interval unit for the trial period.
        field(
          :trial_interval,
          Crystalline::Nilable.new(Models::Components::TrialInterval),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("trial_interval"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::TrialInterval, false)
            }
          }
        )
        # The number of interval units for the trial period.
        field(
          :trial_interval_count,
          Crystalline::Nilable.new(::Integer),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("trial_interval_count"), required: true}}
        )
        # The description of the product.
        field(
          :description,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("description"), required: true}}
        )
        # The recurring interval of the product. If `None`, the product is a one-time purchase.
        field(
          :recurring_interval,
          Crystalline::Nilable.new(Models::Components::SubscriptionRecurringInterval),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("recurring_interval"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(
                Models::Components::SubscriptionRecurringInterval,
                false
              )
            }
          }
        )
        # Number of interval units of the subscription. If this is set to 1 the charge will happen every interval (e.g. every month), if set to 2 it will be every other month, and so on. None for one-time products.
        field(
          :recurring_interval_count,
          Crystalline::Nilable.new(::Integer),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("recurring_interval_count"), required: true}}
        )

        sig {
          params(
            metadata: T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)],
            id: ::String,
            created_at: ::DateTime,
            name: ::String,
            visibility: Models::Components::ProductVisibility,
            is_recurring: T::Boolean,
            is_archived: T::Boolean,
            organization_id: ::String,
            modified_at: T.nilable(::DateTime),
            trial_interval: T.nilable(Models::Components::TrialInterval),
            trial_interval_count: T.nilable(::Integer),
            description: T.nilable(::String),
            recurring_interval: T.nilable(Models::Components::SubscriptionRecurringInterval),
            recurring_interval_count: T.nilable(::Integer)
          )
            .void
        }
        def initialize(
          metadata:,
          id:,
          created_at:,
          name:,
          visibility:,
          is_recurring:,
          is_archived:,
          organization_id:,
          modified_at: nil,
          trial_interval: nil,
          trial_interval_count: nil,
          description: nil,
          recurring_interval: nil,
          recurring_interval_count: nil
        )
          @metadata = metadata
          @id = id
          @created_at = created_at
          @name = name
          @visibility = visibility
          @is_recurring = is_recurring
          @is_archived = is_archived
          @organization_id = organization_id
          @modified_at = modified_at
          @trial_interval = trial_interval
          @trial_interval_count = trial_interval_count
          @description = description
          @recurring_interval = recurring_interval
          @recurring_interval_count = recurring_interval_count
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @metadata == other.metadata
          return false unless @id == other.id
          return false unless @created_at == other.created_at
          return false unless @name == other.name
          return false unless @visibility == other.visibility
          return false unless @is_recurring == other.is_recurring
          return false unless @is_archived == other.is_archived
          return false unless @organization_id == other.organization_id
          return false unless @modified_at == other.modified_at
          return false unless @trial_interval == other.trial_interval
          return false unless @trial_interval_count == other.trial_interval_count
          return false unless @description == other.description
          return false unless @recurring_interval == other.recurring_interval
          return false unless @recurring_interval_count == other.recurring_interval_count
          true
        end
      end
    end
  end
end
