# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class OrganizationSubscriptionSettings
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :allow_multiple_subscriptions,
          Crystalline::Boolean.new,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("allow_multiple_subscriptions"),
              required: true
            }
          }
        )

        field(
          :allow_customer_updates,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("allow_customer_updates"), required: true}}
        )

        field(
          :proration_behavior,
          Models::Components::SubscriptionProrationBehavior,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("proration_behavior"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(
                Models::Components::SubscriptionProrationBehavior,
                false
              )
            }
          }
        )

        field(
          :benefit_revocation_grace_period,
          ::Integer,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("benefit_revocation_grace_period"),
              required: true
            }
          }
        )

        field(
          :prevent_trial_abuse,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("prevent_trial_abuse"), required: true}}
        )

        sig {
          params(
            allow_multiple_subscriptions: T::Boolean,
            allow_customer_updates: T::Boolean,
            proration_behavior: Models::Components::SubscriptionProrationBehavior,
            benefit_revocation_grace_period: ::Integer,
            prevent_trial_abuse: T::Boolean
          )
            .void
        }
        def initialize(
          allow_multiple_subscriptions:,
          allow_customer_updates:,
          proration_behavior:,
          benefit_revocation_grace_period:,
          prevent_trial_abuse:
        )
          @allow_multiple_subscriptions = allow_multiple_subscriptions
          @allow_customer_updates = allow_customer_updates
          @proration_behavior = proration_behavior
          @benefit_revocation_grace_period = benefit_revocation_grace_period
          @prevent_trial_abuse = prevent_trial_abuse
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @allow_multiple_subscriptions == other.allow_multiple_subscriptions
          return false unless @allow_customer_updates == other.allow_customer_updates
          return false unless @proration_behavior == other.proration_behavior
          return false unless @benefit_revocation_grace_period == other.benefit_revocation_grace_period
          return false unless @prevent_trial_abuse == other.prevent_trial_abuse
          true
        end
      end
    end
  end
end
