# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class OrganizationAccessTokenUpdate
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :comment,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("comment")}}
        )

        field(
          :scopes,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::AvailableScope)),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("scopes")}}
        )

        sig {
          params(comment: T.nilable(::String), scopes: T.nilable(T::Array[Models::Components::AvailableScope])).void
        }
        def initialize(comment: nil, scopes: nil)
          @comment = comment
          @scopes = scopes
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @comment == other.comment
          return false unless @scopes == other.scopes
          true
        end
      end
    end
  end
end
