# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class Pagination
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :total_count,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("total_count"), required: true}}
        )

        field(
          :max_page,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("max_page"), required: true}}
        )

        sig { params(total_count: ::Integer, max_page: ::Integer).void }
        def initialize(total_count:, max_page:)
          @total_count = total_count
          @max_page = max_page
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @total_count == other.total_count
          return false unless @max_page == other.max_page
          true
        end
      end
    end
  end
end
