# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class PaymentSortProperty < T::Enum
        enums do
          CREATED_AT = new("created_at")
          MINUS_CREATED_AT = new("-created_at")
          STATUS = new("status")
          MINUS_STATUS = new("-status")
          AMOUNT = new("amount")
          MINUS_AMOUNT = new("-amount")
          METHOD = new("method")
          MINUS_METHOD = new("-method")
        end
      end
    end
  end
end
