# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Schema to create a fixed price.
      class ProductPriceFixedCreate
        extend T::Sig
        include Crystalline::MetadataFields

        # The price in cents.
        field(
          :price_amount,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("price_amount"), required: true}}
        )

        field(
          :amount_type,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("amount_type"), required: true}}
        )

        field(
          :price_currency,
          Crystalline::Nilable.new(Models::Components::PresentmentCurrency),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("price_currency"),
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::PresentmentCurrency, true)
            }
          }
        )

        sig {
          params(
            price_amount: ::Integer,
            amount_type: ::String,
            price_currency: T.nilable(Models::Components::PresentmentCurrency)
          )
            .void
        }
        def initialize(price_amount:, amount_type: "fixed", price_currency: nil)
          @price_amount = price_amount
          unless amount_type == "fixed"
            raise ArgumentError, "Invalid value for amount_type"
          end

          @amount_type = "fixed"
          @price_currency = price_currency
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @price_amount == other.price_amount
          return false unless @amount_type == other.amount_type
          return false unless @price_currency == other.price_currency
          true
        end
      end
    end
  end
end
