# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # A fixed price for a product.
      class ProductPriceFixed
        extend T::Sig
        include Crystalline::MetadataFields

        # Creation timestamp of the object.
        field(
          :created_at,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("created_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # The ID of the price.
        field :id, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("id"), required: true}}

        field(
          :source,
          Models::Components::ProductPriceSource,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("source"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::ProductPriceSource, false)
            }
          }
        )

        field(
          :price_currency,
          Models::Components::PresentmentCurrency,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("price_currency"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::PresentmentCurrency, false)
            }
          }
        )
        # Whether the price is archived and no longer available.
        field(
          :is_archived,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("is_archived"), required: true}}
        )
        # The ID of the product owning the price.
        field(
          :product_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("product_id"), required: true}}
        )

        field(
          :type,
          Models::Components::ProductPriceType,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("type"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::ProductPriceType, false)
            }
          }
        )
        # The price in cents.
        field(
          :price_amount,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("price_amount"), required: true}}
        )
        # Last modification timestamp of the object.
        field(
          :modified_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("modified_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        field(
          :amount_type,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("amount_type"), required: true}}
        )
        # @deprecated true: This will be removed in a future release, please migrate away from it as soon as possible.
        field(
          :recurring_interval,
          Crystalline::Nilable.new(Models::Components::SubscriptionRecurringInterval),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("recurring_interval"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(
                Models::Components::SubscriptionRecurringInterval,
                false
              )
            }
          }
        )

        sig {
          params(
            created_at: ::DateTime,
            id: ::String,
            source: Models::Components::ProductPriceSource,
            price_currency: Models::Components::PresentmentCurrency,
            is_archived: T::Boolean,
            product_id: ::String,
            type: Models::Components::ProductPriceType,
            price_amount: ::Integer,
            modified_at: T.nilable(::DateTime),
            amount_type: ::String,
            recurring_interval: T.nilable(Models::Components::SubscriptionRecurringInterval)
          )
            .void
        }
        def initialize(
          created_at:,
          id:,
          source:,
          price_currency:,
          is_archived:,
          product_id:,
          type:,
          price_amount:,
          modified_at: nil,
          amount_type: "fixed",
          recurring_interval: nil
        )
          @created_at = created_at
          @id = id
          @source = source
          @price_currency = price_currency
          @is_archived = is_archived
          @product_id = product_id
          @type = type
          @price_amount = price_amount
          @modified_at = modified_at
          unless amount_type == "fixed"
            raise ArgumentError, "Invalid value for amount_type"
          end

          @amount_type = "fixed"
          @recurring_interval = recurring_interval
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @created_at == other.created_at
          return false unless @id == other.id
          return false unless @source == other.source
          return false unless @price_currency == other.price_currency
          return false unless @is_archived == other.is_archived
          return false unless @product_id == other.product_id
          return false unless @type == other.type
          return false unless @price_amount == other.price_amount
          return false unless @modified_at == other.modified_at
          return false unless @amount_type == other.amount_type
          return false unless @recurring_interval == other.recurring_interval
          true
        end
      end
    end
  end
end
