# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class PropertyAggregation
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :func,
          Models::Components::Func,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("func"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(Models::Components::Func, false)
            }
          }
        )

        field(
          :property,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("property"), required: true}}
        )

        sig { params(func: Models::Components::Func, property: ::String).void }
        def initialize(func:, property:)
          @func = func
          @property = property
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @func == other.func
          return false unless @property == other.property
          true
        end
      end
    end
  end
end
