# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class QuizAnswerResult
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :question_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("question_id"), required: true}}
        )

        field(
          :correct,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("correct"), required: true}}
        )

        field(
          :correct_option_ids,
          Crystalline::Array.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("correct_option_ids"), required: true}}
        )

        field(
          :explanations,
          Crystalline::Hash.new(Symbol, ::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("explanations"), required: true}}
        )

        sig {
          params(
            question_id: ::String,
            correct: T::Boolean,
            correct_option_ids: T::Array[::String],
            explanations: T::Hash[Symbol, ::String]
          )
            .void
        }
        def initialize(question_id:, correct:, correct_option_ids:, explanations:)
          @question_id = question_id
          @correct = correct
          @correct_option_ids = correct_option_ids
          @explanations = explanations
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @question_id == other.question_id
          return false unless @correct == other.correct
          return false unless @correct_option_ids == other.correct_option_ids
          return false unless @explanations == other.explanations
          true
        end
      end
    end
  end
end
