# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class QuizAttemptSubmission
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :answers,
          Crystalline::Array.new(Models::Components::QuizAnswerSubmission),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("answers"), required: true}}
        )

        sig { params(answers: T::Array[Models::Components::QuizAnswerSubmission]).void }
        def initialize(answers:)
          @answers = answers
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @answers == other.answers
          true
        end
      end
    end
  end
end
