# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class S3DownloadURL
        extend T::Sig
        include Crystalline::MetadataFields

        field :url, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("url"), required: true}}

        field(
          :expires_at,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("expires_at"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        field(
          :headers,
          Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::String)),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("headers")}}
        )

        sig { params(url: ::String, expires_at: ::DateTime, headers: T.nilable(T::Hash[Symbol, ::String])).void }
        def initialize(url:, expires_at:, headers: nil)
          @url = url
          @expires_at = expires_at
          @headers = headers
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @url == other.url
          return false unless @expires_at == other.expires_at
          return false unless @headers == other.headers
          true
        end
      end
    end
  end
end
