# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class S3FileCreatePart
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :number,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("number"), required: true}}
        )

        field(
          :chunk_start,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("chunk_start"), required: true}}
        )

        field(
          :chunk_end,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("chunk_end"), required: true}}
        )

        field(
          :checksum_sha256_base64,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("checksum_sha256_base64")}}
        )

        sig {
          params(
            number: ::Integer,
            chunk_start: ::Integer,
            chunk_end: ::Integer,
            checksum_sha256_base64: T.nilable(::String)
          )
            .void
        }
        def initialize(number:, chunk_start:, chunk_end:, checksum_sha256_base64: nil)
          @number = number
          @chunk_start = chunk_start
          @chunk_end = chunk_end
          @checksum_sha256_base64 = checksum_sha256_base64
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @number == other.number
          return false unless @chunk_start == other.chunk_start
          return false unless @chunk_end == other.chunk_end
          return false unless @checksum_sha256_base64 == other.checksum_sha256_base64
          true
        end
      end
    end
  end
end
