# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class S3FileUploadCompletedPart
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :number,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("number"), required: true}}
        )

        field(
          :checksum_etag,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("checksum_etag"), required: true}}
        )

        field(
          :checksum_sha256_base64,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("checksum_sha256_base64"), required: true}}
        )

        sig { params(number: ::Integer, checksum_etag: ::String, checksum_sha256_base64: T.nilable(::String)).void }
        def initialize(number:, checksum_etag:, checksum_sha256_base64: nil)
          @number = number
          @checksum_etag = checksum_etag
          @checksum_sha256_base64 = checksum_sha256_base64
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @number == other.number
          return false unless @checksum_etag == other.checksum_etag
          return false unless @checksum_sha256_base64 == other.checksum_sha256_base64
          true
        end
      end
    end
  end
end
