# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class Security
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :access_token,
          Crystalline::Nilable.new(::String),
          {'security': {'scheme': true, 'type': "http", 'sub_type': "bearer", 'field_name': "Authorization"}}
        )

        sig { params(access_token: T.nilable(::String)).void }
        def initialize(access_token: nil)
          @access_token = access_token
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @access_token == other.access_token
          true
        end
      end
    end
  end
end
