# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class Status
        include ::Crystalline::Enum
        enums do
          ACTIVE = new("active")
          TRIALING = new("trialing")
        end

        open!
      end
    end
  end
end
