# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class SubscriptionUpdateProduct
        extend T::Sig
        include Crystalline::MetadataFields

        # Update subscription to another product.
        field(
          :product_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("product_id"), required: true}}
        )
        # Determine how to handle the proration billing. If not provided, will use the default organization setting.
        field(
          :proration_behavior,
          Crystalline::Nilable.new(Models::Components::SubscriptionProrationBehavior),
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("proration_behavior"),
              'decoder': ::OpenApiSDK::Utils.open_enum_from_string(
                Models::Components::SubscriptionProrationBehavior,
                true
              )
            }
          }
        )

        sig {
          params(product_id: ::String, proration_behavior: T.nilable(Models::Components::SubscriptionProrationBehavior))
            .void
        }
        def initialize(product_id:, proration_behavior: nil)
          @product_id = product_id
          @proration_behavior = proration_behavior
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @product_id == other.product_id
          return false unless @proration_behavior == other.proration_behavior
          true
        end
      end
    end
  end
end
