# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class SubscriptionUpdateBillingPeriod
        extend T::Sig
        include Crystalline::MetadataFields

        # Set a new date for the end of the current billing period. The subscription will renew on this date. Needs to be later than the current value.
        #
        # It is not possible to update the current billing period on a canceled subscription.
        field(
          :current_billing_period_end,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("current_billing_period_end"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        sig { params(current_billing_period_end: ::DateTime).void }
        def initialize(current_billing_period_end:)
          @current_billing_period_end = current_billing_period_end
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @current_billing_period_end == other.current_billing_period_end
          true
        end
      end
    end
  end
end
