# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # An event created by Spaire when a subscription is canceled.
      class SubscriptionCanceledEvent
        extend T::Sig
        include Crystalline::MetadataFields

        # The ID of the object.
        field :id, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("id"), required: true}}
        # The timestamp of the event.
        field(
          :timestamp,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("timestamp"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )
        # The ID of the organization owning the event.
        field(
          :organization_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("organization_id"), required: true}}
        )
        # Human readable label of the event type.
        field(
          :label,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("label"), required: true}}
        )

        field(
          :metadata,
          Models::Components::SubscriptionCanceledMetadata,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("metadata"), required: true}}
        )
        # ID of the customer in your Spaire organization associated with the event.
        field(
          :customer_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("customer_id"), required: true}}
        )
        # The customer associated with the event.
        field(
          :customer,
          Crystalline::Nilable.new(Models::Components::Customer),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("customer"), required: true}}
        )
        # ID of the customer in your system associated with the event.
        field(
          :external_customer_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("external_customer_id"), required: true}}
        )
        # The source of the event. `system` events are created by Spaire. `user` events are the one you create through our ingestion API.
        field(
          :source,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("source"), required: true}}
        )
        # The name of the event.
        field :name, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("name"), required: true}}
        # ID of the member within the customer's organization who performed the action inside B2B.
        field(
          :member_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("member_id")}}
        )
        # ID of the member in your system within the customer's organization who performed the action inside B2B.
        field(
          :external_member_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("external_member_id")}}
        )
        # Number of direct child events linked to this event.
        field(
          :child_count,
          Crystalline::Nilable.new(::Integer),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("child_count")}}
        )
        # The ID of the parent event.
        field(
          :parent_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("parent_id")}}
        )

        sig {
          params(
            id: ::String,
            timestamp: ::DateTime,
            organization_id: ::String,
            label: ::String,
            metadata: Models::Components::SubscriptionCanceledMetadata,
            customer_id: T.nilable(::String),
            customer: T.nilable(Models::Components::Customer),
            external_customer_id: T.nilable(::String),
            source: ::String,
            name: ::String,
            member_id: T.nilable(::String),
            external_member_id: T.nilable(::String),
            child_count: T.nilable(::Integer),
            parent_id: T.nilable(::String)
          )
            .void
        }
        def initialize(
          id:,
          timestamp:,
          organization_id:,
          label:,
          metadata:,
          customer_id: nil,
          customer: nil,
          external_customer_id: nil,
          source: "system",
          name: "subscription.canceled",
          member_id: nil,
          external_member_id: nil,
          child_count: 0,
          parent_id: nil
        )
          @id = id
          @timestamp = timestamp
          @organization_id = organization_id
          @label = label
          @metadata = metadata
          @customer_id = customer_id
          @customer = customer
          @external_customer_id = external_customer_id
          unless source == "system"
            raise ArgumentError, "Invalid value for source"
          end

          @source = "system"
          unless name == "subscription.canceled"
            raise ArgumentError, "Invalid value for name"
          end

          @name = "subscription.canceled"
          @member_id = member_id
          @external_member_id = external_member_id
          @child_count = child_count
          @parent_id = parent_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @id == other.id
          return false unless @timestamp == other.timestamp
          return false unless @organization_id == other.organization_id
          return false unless @label == other.label
          return false unless @metadata == other.metadata
          return false unless @customer_id == other.customer_id
          return false unless @customer == other.customer
          return false unless @external_customer_id == other.external_customer_id
          return false unless @source == other.source
          return false unless @name == other.name
          return false unless @member_id == other.member_id
          return false unless @external_member_id == other.external_member_id
          return false unless @child_count == other.child_count
          return false unless @parent_id == other.parent_id
          true
        end
      end
    end
  end
end
