# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class SubscriptionSortProperty < T::Enum
        enums do
          CUSTOMER = new("customer")
          MINUS_CUSTOMER = new("-customer")
          STATUS = new("status")
          MINUS_STATUS = new("-status")
          STARTED_AT = new("started_at")
          MINUS_STARTED_AT = new("-started_at")
          CURRENT_PERIOD_END = new("current_period_end")
          MINUS_CURRENT_PERIOD_END = new("-current_period_end")
          ENDED_AT = new("ended_at")
          MINUS_ENDED_AT = new("-ended_at")
          ENDS_AT = new("ends_at")
          MINUS_ENDS_AT = new("-ends_at")
          AMOUNT = new("amount")
          MINUS_AMOUNT = new("-amount")
          PRODUCT = new("product")
          MINUS_PRODUCT = new("-product")
          DISCOUNT = new("discount")
          MINUS_DISCOUNT = new("-discount")
        end
      end
    end
  end
end
