# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class SubscriptionSeatsUpdatedMetadata
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :subscription_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("subscription_id"), required: true}}
        )

        field(
          :old_seats,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("old_seats"), required: true}}
        )

        field(
          :new_seats,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("new_seats"), required: true}}
        )

        field(
          :proration_behavior,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("proration_behavior"), required: true}}
        )

        sig {
          params(subscription_id: ::String, old_seats: ::Integer, new_seats: ::Integer, proration_behavior: ::String)
            .void
        }
        def initialize(subscription_id:, old_seats:, new_seats:, proration_behavior:)
          @subscription_id = subscription_id
          @old_seats = old_seats
          @new_seats = new_seats
          @proration_behavior = proration_behavior
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @subscription_id == other.subscription_id
          return false unless @old_seats == other.old_seats
          return false unless @new_seats == other.new_seats
          return false unless @proration_behavior == other.proration_behavior
          true
        end
      end
    end
  end
end
