# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Create a subscription for an existing customer identified by an external ID.
      class SubscriptionCreateExternalCustomer
        extend T::Sig
        include Crystalline::MetadataFields

        # The ID of the recurring product to subscribe to. Must be a free product, otherwise the customer should go through a checkout flow.
        field(
          :product_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("product_id"), required: true}}
        )
        # The ID of the customer in your system to create the subscription for. It must already exist in Spaire.
        field(
          :external_customer_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("external_customer_id"), required: true}}
        )
        # Key-value object allowing you to store additional information.
        #
        # The key must be a string with a maximum length of **40 characters**.
        # The value must be either:
        #
        # * A string with a maximum length of **500 characters**
        # * An integer
        # * A floating-point number
        # * A boolean
        #
        # You can store up to **50 key-value pairs**.
        field(
          :metadata,
          Crystalline::Nilable.new(
            Crystalline::Hash.new(
              Symbol,
              Crystalline::Union.new(::String, ::Integer, ::Float, Crystalline::Boolean.new)
            )
          ),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("metadata")}}
        )

        sig {
          params(
            product_id: ::String,
            external_customer_id: ::String,
            metadata: T.nilable(T::Hash[Symbol, T.any(::String, ::Integer, ::Float, T::Boolean)])
          )
            .void
        }
        def initialize(product_id:, external_customer_id:, metadata: nil)
          @product_id = product_id
          @external_customer_id = external_customer_id
          @metadata = metadata
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @product_id == other.product_id
          return false unless @external_customer_id == other.external_customer_id
          return false unless @metadata == other.metadata
          true
        end
      end
    end
  end
end
