# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class SubscriptionUncanceledMetadata
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :subscription_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("subscription_id"), required: true}}
        )

        field(
          :product_id,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("product_id"), required: true}}
        )

        field(
          :amount,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("amount"), required: true}}
        )

        field(
          :currency,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("currency"), required: true}}
        )

        field(
          :recurring_interval,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("recurring_interval"), required: true}}
        )

        field(
          :recurring_interval_count,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("recurring_interval_count"), required: true}}
        )

        sig {
          params(
            subscription_id: ::String,
            product_id: ::String,
            amount: ::Integer,
            currency: ::String,
            recurring_interval: ::String,
            recurring_interval_count: ::Integer
          )
            .void
        }
        def initialize(
          subscription_id:,
          product_id:,
          amount:,
          currency:,
          recurring_interval:,
          recurring_interval_count:
        )
          @subscription_id = subscription_id
          @product_id = product_id
          @amount = amount
          @currency = currency
          @recurring_interval = recurring_interval
          @recurring_interval_count = recurring_interval_count
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @subscription_id == other.subscription_id
          return false unless @product_id == other.product_id
          return false unless @amount == other.amount
          return false unless @currency == other.currency
          return false unless @recurring_interval == other.recurring_interval
          return false unless @recurring_interval_count == other.recurring_interval_count
          true
        end
      end
    end
  end
end
