# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class SubType
        include ::Crystalline::Enum
        enums do
          USER = new("user")
          ORGANIZATION = new("organization")
        end

        open!
      end
    end
  end
end
