# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class TaxBehaviorOption
        include ::Crystalline::Enum
        enums do
          LOCATION = new("location")
          INCLUSIVE = new("inclusive")
          EXCLUSIVE = new("exclusive")
        end

        open!
      end
    end
  end
end
