# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class TaxRatePreview
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :display_name,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("display_name"), required: true}}
        )

        field(
          :percentage,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("percentage")}}
        )

        sig { params(display_name: ::String, percentage: T.nilable(::Float)).void }
        def initialize(display_name:, percentage: nil)
          @display_name = display_name
          @percentage = percentage
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @display_name == other.display_name
          return false unless @percentage == other.percentage
          true
        end
      end
    end
  end
end
