# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class TokenResponse
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :access_token,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("access_token"), required: true}}
        )

        field(
          :expires_in,
          ::Integer,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("expires_in"), required: true}}
        )

        field(
          :scope,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("scope"), required: true}}
        )

        field(
          :id_token,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("id_token"), required: true}}
        )

        field(
          :token_type,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("token_type"), required: true}}
        )

        field(
          :refresh_token,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("refresh_token"), required: true}}
        )

        sig {
          params(
            access_token: ::String,
            expires_in: ::Integer,
            scope: ::String,
            id_token: ::String,
            token_type: ::String,
            refresh_token: T.nilable(::String)
          )
            .void
        }
        def initialize(access_token:, expires_in:, scope:, id_token:, token_type: "Bearer", refresh_token: nil)
          @access_token = access_token
          @expires_in = expires_in
          @scope = scope
          @id_token = id_token
          unless token_type == "Bearer"
            raise ArgumentError, "Invalid value for token_type"
          end

          @token_type = "Bearer"
          @refresh_token = refresh_token
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @access_token == other.access_token
          return false unless @expires_in == other.expires_in
          return false unless @scope == other.scope
          return false unless @id_token == other.id_token
          return false unless @token_type == other.token_type
          return false unless @refresh_token == other.refresh_token
          true
        end
      end
    end
  end
end
