# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Type - Link type
      class Type
        include ::Crystalline::Enum
        enums do
          STANDARD = new("standard")
          EMBEDDED = new("embedded")
        end

        open!
      end
    end
  end
end
