# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class UniqueAggregation
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :property,
          ::String,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("property"), required: true}}
        )

        field(
          :func,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("func")}}
        )

        sig { params(property: ::String, func: T.nilable(::String)).void }
        def initialize(property:, func: "unique")
          @property = property
          unless func == "unique"
            raise ArgumentError, "Invalid value for func"
          end

          @func = "unique"
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @property == other.property
          return false unless @func == other.func
          true
        end
      end
    end
  end
end
