# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class UserInfoOrganization
        extend T::Sig
        include Crystalline::MetadataFields

        field :sub, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("sub"), required: true}}

        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("name")}}
        )

        sig { params(sub: ::String, name: T.nilable(::String)).void }
        def initialize(sub:, name: nil)
          @sub = sub
          @name = name
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @sub == other.sub
          return false unless @name == other.name
          true
        end
      end
    end
  end
end
