# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Sent when a benefit grant is updated.
      #
      # **Discord & Slack support:** Basic
      class WebhookBenefitGrantUpdatedPayload
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :timestamp,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("timestamp"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        field(
          :data,
          Crystalline::Union.new(
            Models::Components::BenefitGrantDiscordWebhook,
            Models::Components::BenefitGrantCustomWebhook,
            Models::Components::BenefitGrantGitHubRepositoryWebhook,
            Models::Components::BenefitGrantDownloadablesWebhook,
            Models::Components::BenefitGrantLicenseKeysWebhook,
            Models::Components::BenefitGrantMeterCreditWebhook
          ),
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("data"), required: true}}
        )

        field :type, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("type"), required: true}}

        sig {
          params(
            timestamp: ::DateTime,
            data: T.any(
              Models::Components::BenefitGrantDiscordWebhook,
              Models::Components::BenefitGrantCustomWebhook,
              Models::Components::BenefitGrantGitHubRepositoryWebhook,
              Models::Components::BenefitGrantDownloadablesWebhook,
              Models::Components::BenefitGrantLicenseKeysWebhook,
              Models::Components::BenefitGrantMeterCreditWebhook
            ),
            type: ::String
          )
            .void
        }
        def initialize(timestamp:, data:, type: "benefit_grant.updated")
          @timestamp = timestamp
          @data = data
          unless type == "benefit_grant.updated"
            raise ArgumentError, "Invalid value for type"
          end

          @type = "benefit_grant.updated"
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @timestamp == other.timestamp
          return false unless @data == other.data
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
