# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      # Sent when a subscription is revoked and the user loses access immediately.
      # Happens when the subscription is canceled or payment retries are exhausted (status becomes `unpaid`).
      #
      # For payment failures that can still be recovered, see `subscription.past_due`.
      #
      # **Discord & Slack support:** Full
      class WebhookSubscriptionRevokedPayload
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :timestamp,
          ::DateTime,
          {
            'format_json': {
              'letter_case': ::OpenApiSDK::Utils.field_name("timestamp"),
              required: true,
              'decoder': ::OpenApiSDK::Utils.datetime_from_iso_format(false)
            }
          }
        )

        field(
          :data,
          Models::Components::Subscription,
          {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("data"), required: true}}
        )

        field :type, ::String, {'format_json': {'letter_case': ::OpenApiSDK::Utils.field_name("type"), required: true}}

        sig { params(timestamp: ::DateTime, data: Models::Components::Subscription, type: ::String).void }
        def initialize(timestamp:, data:, type: "subscription.revoked")
          @timestamp = timestamp
          @data = data
          unless type == "subscription.revoked"
            raise ArgumentError, "Invalid value for type"
          end

          @type = "subscription.revoked"
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @timestamp == other.timestamp
          return false unless @data == other.data
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
