# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components

      class WhoCanPost
        include ::Crystalline::Enum
        enums do
          EVERYONE = new("everyone")
          APPROVED = new("approved")
        end

        open!
      end
    end
  end
end
