# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations

      class BenefitsListRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter by organization ID.
        field(
          :organization_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "organization_id", 'style': "form", 'explode': true}}
        )
        # Filter by benefit type.
        field(
          :type_filter,
          Crystalline::Nilable.new(
            Crystalline::Union.new(
              Models::Components::BenefitType,
              Crystalline::Array.new(Models::Components::BenefitType)
            )
          ),
          {'query_param': {'field_name': "type", 'style': "form", 'explode': true}}
        )
        # Filter by benefit IDs.
        field(
          :id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "id", 'style': "form", 'explode': true}}
        )
        # Exclude benefits with these IDs.
        field(
          :exclude_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "exclude_id", 'style': "form", 'explode': true}}
        )
        # Filter by description.
        field(
          :query,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "query", 'style': "form", 'explode': true}}
        )
        # Page number, defaults to 1.
        field(
          :page,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "page", 'style': "form", 'explode': true}}
        )
        # Size of a page, defaults to 10. Maximum is 100.
        field(
          :limit,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "limit", 'style': "form", 'explode': true}}
        )
        # Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
        field(
          :sorting,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::BenefitSortProperty)),
          {'query_param': {'field_name': "sorting", 'style': "form", 'explode': true}}
        )
        # Filter by metadata key-value pairs. It uses the `deepObject` style, e.g. `?metadata[key]=value`.
        field(
          :metadata,
          Crystalline::Nilable.new(
            Crystalline::Hash.new(
              Symbol,
              Crystalline::Union.new(
                ::String,
                ::Integer,
                Crystalline::Boolean.new,
                Crystalline::Array.new(::String),
                Crystalline::Array.new(::Integer),
                Crystalline::Array.new(Crystalline::Boolean.new)
              )
            )
          ),
          {'query_param': {'field_name': "metadata", 'style': "deepObject", 'explode': true}}
        )

        sig {
          params(
            organization_id: T.nilable(T.any(::String, T::Array[::String])),
            type_filter: T.nilable(T.any(Models::Components::BenefitType, T::Array[Models::Components::BenefitType])),
            id: T.nilable(T.any(::String, T::Array[::String])),
            exclude_id: T.nilable(T.any(::String, T::Array[::String])),
            query: T.nilable(::String),
            page: T.nilable(::Integer),
            limit: T.nilable(::Integer),
            sorting: T.nilable(T::Array[Models::Components::BenefitSortProperty]),
            metadata: T.nilable(
              T::Hash[
                Symbol,
                T.any(::String, ::Integer, T::Boolean, T::Array[::String], T::Array[::Integer], T::Array[T::Boolean])
              ]
            )
          )
            .void
        }
        def initialize(
          organization_id: nil,
          type_filter: nil,
          id: nil,
          exclude_id: nil,
          query: nil,
          page: 1,
          limit: 10,
          sorting: nil,
          metadata: nil
        )
          @organization_id = organization_id
          @type_filter = type_filter
          @id = id
          @exclude_id = exclude_id
          @query = query
          @page = page
          @limit = limit
          @sorting = sorting
          @metadata = metadata
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @organization_id == other.organization_id
          return false unless @type_filter == other.type_filter
          return false unless @id == other.id
          return false unless @exclude_id == other.exclude_id
          return false unless @query == other.query
          return false unless @page == other.page
          return false unless @limit == other.limit
          return false unless @sorting == other.sorting
          return false unless @metadata == other.metadata
          true
        end
      end
    end
  end
end
