# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations

      class CustomerPortalCustomerPortalCoursesListLessonCommentsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        field :course_id, ::String, {'path_param': {'field_name': "course_id", 'style': "simple", 'explode': false}}

        field :lesson_id, ::String, {'path_param': {'field_name': "lesson_id", 'style': "simple", 'explode': false}}

        sig { params(course_id: ::String, lesson_id: ::String).void }
        def initialize(course_id:, lesson_id:)
          @course_id = course_id
          @lesson_id = lesson_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @course_id == other.course_id
          return false unless @lesson_id == other.lesson_id
          true
        end
      end
    end
  end
end
