# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations

      class CustomerPortalCommunityUploadPostImageRequest
        extend T::Sig
        include Crystalline::MetadataFields

        field :course_id, ::String, {'path_param': {'field_name': "course_id", 'style': "simple", 'explode': false}}

        field(
          :body,
          Models::Components::BodyCustomerPortalCommunityUploadPostImage,
          {'request': {'media_type': "multipart/form-data"}}
        )

        sig { params(course_id: ::String, body: Models::Components::BodyCustomerPortalCommunityUploadPostImage).void }
        def initialize(course_id:, body:)
          @course_id = course_id
          @body = body
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @course_id == other.course_id
          return false unless @body == other.body
          true
        end
      end
    end
  end
end
