# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations

      class CustomFieldsListRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter by organization ID.
        field(
          :organization_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "organization_id", 'style': "form", 'explode': true}}
        )
        # Filter by custom field name or slug.
        field(
          :query,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "query", 'style': "form", 'explode': true}}
        )
        # Filter by custom field type.
        field(
          :type_filter,
          Crystalline::Nilable.new(
            Crystalline::Union.new(
              Models::Components::CustomFieldType,
              Crystalline::Array.new(Models::Components::CustomFieldType)
            )
          ),
          {'query_param': {'field_name': "type", 'style': "form", 'explode': true}}
        )
        # Page number, defaults to 1.
        field(
          :page,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "page", 'style': "form", 'explode': true}}
        )
        # Size of a page, defaults to 10. Maximum is 100.
        field(
          :limit,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "limit", 'style': "form", 'explode': true}}
        )
        # Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
        field(
          :sorting,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::CustomFieldSortProperty)),
          {'query_param': {'field_name': "sorting", 'style': "form", 'explode': true}}
        )

        sig {
          params(
            organization_id: T.nilable(T.any(::String, T::Array[::String])),
            query: T.nilable(::String),
            type_filter: T.nilable(
              T.any(Models::Components::CustomFieldType, T::Array[Models::Components::CustomFieldType])
            ),
            page: T.nilable(::Integer),
            limit: T.nilable(::Integer),
            sorting: T.nilable(T::Array[Models::Components::CustomFieldSortProperty])
          )
            .void
        }
        def initialize(organization_id: nil, query: nil, type_filter: nil, page: 1, limit: 10, sorting: nil)
          @organization_id = organization_id
          @query = query
          @type_filter = type_filter
          @page = page
          @limit = limit
          @sorting = sorting
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @organization_id == other.organization_id
          return false unless @query == other.query
          return false unless @type_filter == other.type_filter
          return false unless @page == other.page
          return false unless @limit == other.limit
          return false unless @sorting == other.sorting
          true
        end
      end
    end
  end
end
