# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations

      class EventsListNamesRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter by organization ID.
        field(
          :organization_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "organization_id", 'style': "form", 'explode': true}}
        )
        # Filter by customer ID.
        field(
          :customer_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "customer_id", 'style': "form", 'explode': true}}
        )
        # Filter by external customer ID.
        field(
          :external_customer_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "external_customer_id", 'style': "form", 'explode': true}}
        )
        # Filter by event source.
        field(
          :source,
          Crystalline::Nilable.new(
            Crystalline::Union.new(
              Models::Components::EventSource,
              Crystalline::Array.new(Models::Components::EventSource)
            )
          ),
          {'query_param': {'field_name': "source", 'style': "form", 'explode': true}}
        )
        # Query to filter event names.
        field(
          :query,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "query", 'style': "form", 'explode': true}}
        )
        # Page number, defaults to 1.
        field(
          :page,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "page", 'style': "form", 'explode': true}}
        )
        # Size of a page, defaults to 10. Maximum is 100.
        field(
          :limit,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "limit", 'style': "form", 'explode': true}}
        )
        # Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
        field(
          :sorting,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::EventNamesSortProperty)),
          {'query_param': {'field_name': "sorting", 'style': "form", 'explode': true}}
        )

        sig {
          params(
            organization_id: T.nilable(T.any(::String, T::Array[::String])),
            customer_id: T.nilable(T.any(::String, T::Array[::String])),
            external_customer_id: T.nilable(T.any(::String, T::Array[::String])),
            source: T.nilable(T.any(Models::Components::EventSource, T::Array[Models::Components::EventSource])),
            query: T.nilable(::String),
            page: T.nilable(::Integer),
            limit: T.nilable(::Integer),
            sorting: T.nilable(T::Array[Models::Components::EventNamesSortProperty])
          )
            .void
        }
        def initialize(
          organization_id: nil,
          customer_id: nil,
          external_customer_id: nil,
          source: nil,
          query: nil,
          page: 1,
          limit: 10,
          sorting: nil
        )
          @organization_id = organization_id
          @customer_id = customer_id
          @external_customer_id = external_customer_id
          @source = source
          @query = query
          @page = page
          @limit = limit
          @sorting = sorting
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @organization_id == other.organization_id
          return false unless @customer_id == other.customer_id
          return false unless @external_customer_id == other.external_customer_id
          return false unless @source == other.source
          return false unless @query == other.query
          return false unless @page == other.page
          return false unless @limit == other.limit
          return false unless @sorting == other.sorting
          true
        end
      end
    end
  end
end
