# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations
      # HttpCodeClass - Filter by HTTP response code class (2xx, 3xx, 4xx, 5xx).
      class HttpCodeClass < T::Enum
        enums do
          TWOXX = new("2xx")
          THREEXX = new("3xx")
          FOURXX = new("4xx")
          FIVEXX = new("5xx")
        end
      end
    end
  end
end
