# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations

      class LicenseKeysGetActivationRequest
        extend T::Sig
        include Crystalline::MetadataFields

        field :id, ::String, {'path_param': {'field_name': "id", 'style': "simple", 'explode': false}}

        field(
          :activation_id,
          ::String,
          {'path_param': {'field_name': "activation_id", 'style': "simple", 'explode': false}}
        )

        sig { params(id: ::String, activation_id: ::String).void }
        def initialize(id:, activation_id:)
          @id = id
          @activation_id = activation_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @id == other.id
          return false unless @activation_id == other.activation_id
          true
        end
      end
    end
  end
end
