# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations

      class Oauth2ClientsOauth2UpdateClientRequest
        extend T::Sig
        include Crystalline::MetadataFields

        field :client_id, ::String, {'path_param': {'field_name': "client_id", 'style': "simple", 'explode': false}}

        field(
          :body,
          Models::Components::OAuth2ClientConfigurationUpdate,
          {'request': {'media_type': "application/json"}}
        )

        sig { params(client_id: ::String, body: Models::Components::OAuth2ClientConfigurationUpdate).void }
        def initialize(client_id:, body:)
          @client_id = client_id
          @body = body
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @client_id == other.client_id
          return false unless @body == other.body
          true
        end
      end
    end
  end
end
