# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations

      class Oauth2AuthorizeResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # Successful Response
        field(
          :response_oauth2_authorize,
          Crystalline::Nilable.new(
            Crystalline::DiscriminatedUnion.new(
              "sub_type",
              {
                "user" => Models::Components::AuthorizeResponseUser,
                "organization" => Models::Components::AuthorizeResponseOrganization
              }
            )
          )
        )

        sig {
          params(
            content_type: ::String,
            status_code: ::Integer,
            raw_response: ::Faraday::Response,
            response_oauth2_authorize: T.nilable(
              T.any(Models::Components::AuthorizeResponseUser, Models::Components::AuthorizeResponseOrganization)
            )
          )
            .void
        }
        def initialize(content_type:, status_code:, raw_response:, response_oauth2_authorize: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @response_oauth2_authorize = response_oauth2_authorize
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @response_oauth2_authorize == other.response_oauth2_authorize
          true
        end
      end
    end
  end
end
