# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations

      class PaymentsListRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter by organization ID.
        field(
          :organization_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "organization_id", 'style': "form", 'explode': true}}
        )
        # Filter by checkout ID.
        field(
          :checkout_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "checkout_id", 'style': "form", 'explode': true}}
        )
        # Filter by order ID.
        field(
          :order_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "order_id", 'style': "form", 'explode': true}}
        )
        # Filter by payment status.
        field(
          :status,
          Crystalline::Nilable.new(
            Crystalline::Union.new(
              Models::Components::PaymentStatus,
              Crystalline::Array.new(Models::Components::PaymentStatus)
            )
          ),
          {'query_param': {'field_name': "status", 'style': "form", 'explode': true}}
        )
        # Filter by payment method.
        field(
          :method,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "method", 'style': "form", 'explode': true}}
        )
        # Filter by customer email.
        field(
          :customer_email,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "customer_email", 'style': "form", 'explode': true}}
        )
        # Page number, defaults to 1.
        field(
          :page,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "page", 'style': "form", 'explode': true}}
        )
        # Size of a page, defaults to 10. Maximum is 100.
        field(
          :limit,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "limit", 'style': "form", 'explode': true}}
        )
        # Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
        field(
          :sorting,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::PaymentSortProperty)),
          {'query_param': {'field_name': "sorting", 'style': "form", 'explode': true}}
        )

        sig {
          params(
            organization_id: T.nilable(T.any(::String, T::Array[::String])),
            checkout_id: T.nilable(T.any(::String, T::Array[::String])),
            order_id: T.nilable(T.any(::String, T::Array[::String])),
            status: T.nilable(T.any(Models::Components::PaymentStatus, T::Array[Models::Components::PaymentStatus])),
            method: T.nilable(T.any(::String, T::Array[::String])),
            customer_email: T.nilable(T.any(::String, T::Array[::String])),
            page: T.nilable(::Integer),
            limit: T.nilable(::Integer),
            sorting: T.nilable(T::Array[Models::Components::PaymentSortProperty])
          )
            .void
        }
        def initialize(
          organization_id: nil,
          checkout_id: nil,
          order_id: nil,
          status: nil,
          method: nil,
          customer_email: nil,
          page: 1,
          limit: 10,
          sorting: nil
        )
          @organization_id = organization_id
          @checkout_id = checkout_id
          @order_id = order_id
          @status = status
          @method = method
          @customer_email = customer_email
          @page = page
          @limit = limit
          @sorting = sorting
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @organization_id == other.organization_id
          return false unless @checkout_id == other.checkout_id
          return false unless @order_id == other.order_id
          return false unless @status == other.status
          return false unless @method == other.method
          return false unless @customer_email == other.customer_email
          return false unless @page == other.page
          return false unless @limit == other.limit
          return false unless @sorting == other.sorting
          true
        end
      end
    end
  end
end
