# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations

      class RefundsListRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter by refund ID.
        field(
          :id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "id", 'style': "form", 'explode': true}}
        )
        # Filter by organization ID.
        field(
          :organization_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "organization_id", 'style': "form", 'explode': true}}
        )
        # Filter by order ID.
        field(
          :order_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "order_id", 'style': "form", 'explode': true}}
        )
        # Filter by subscription ID.
        field(
          :subscription_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "subscription_id", 'style': "form", 'explode': true}}
        )
        # Filter by customer ID.
        field(
          :customer_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "customer_id", 'style': "form", 'explode': true}}
        )
        # Filter by customer external ID.
        field(
          :external_customer_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "external_customer_id", 'style': "form", 'explode': true}}
        )
        # Filter by `succeeded`.
        field(
          :succeeded,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'query_param': {'field_name': "succeeded", 'style': "form", 'explode': true}}
        )
        # Page number, defaults to 1.
        field(
          :page,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "page", 'style': "form", 'explode': true}}
        )
        # Size of a page, defaults to 10. Maximum is 100.
        field(
          :limit,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "limit", 'style': "form", 'explode': true}}
        )
        # Sorting criterion. Several criteria can be used simultaneously and will be applied in order. Add a minus sign `-` before the criteria name to sort by descending order.
        field(
          :sorting,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::RefundSortProperty)),
          {'query_param': {'field_name': "sorting", 'style': "form", 'explode': true}}
        )

        sig {
          params(
            id: T.nilable(T.any(::String, T::Array[::String])),
            organization_id: T.nilable(T.any(::String, T::Array[::String])),
            order_id: T.nilable(T.any(::String, T::Array[::String])),
            subscription_id: T.nilable(T.any(::String, T::Array[::String])),
            customer_id: T.nilable(T.any(::String, T::Array[::String])),
            external_customer_id: T.nilable(T.any(::String, T::Array[::String])),
            succeeded: T.nilable(T::Boolean),
            page: T.nilable(::Integer),
            limit: T.nilable(::Integer),
            sorting: T.nilable(T::Array[Models::Components::RefundSortProperty])
          )
            .void
        }
        def initialize(
          id: nil,
          organization_id: nil,
          order_id: nil,
          subscription_id: nil,
          customer_id: nil,
          external_customer_id: nil,
          succeeded: nil,
          page: 1,
          limit: 10,
          sorting: nil
        )
          @id = id
          @organization_id = organization_id
          @order_id = order_id
          @subscription_id = subscription_id
          @customer_id = customer_id
          @external_customer_id = external_customer_id
          @succeeded = succeeded
          @page = page
          @limit = limit
          @sorting = sorting
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @id == other.id
          return false unless @organization_id == other.organization_id
          return false unless @order_id == other.order_id
          return false unless @subscription_id == other.subscription_id
          return false unless @customer_id == other.customer_id
          return false unless @external_customer_id == other.external_customer_id
          return false unless @succeeded == other.succeeded
          return false unless @page == other.page
          return false unless @limit == other.limit
          return false unless @sorting == other.sorting
          true
        end
      end
    end
  end
end
