# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations

      class WebhooksListWebhookEndpointsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter by organization ID.
        field(
          :organization_id,
          Crystalline::Nilable.new(Crystalline::Union.new(::String, Crystalline::Array.new(::String))),
          {'query_param': {'field_name': "organization_id", 'style': "form", 'explode': true}}
        )
        # Page number, defaults to 1.
        field(
          :page,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "page", 'style': "form", 'explode': true}}
        )
        # Size of a page, defaults to 10. Maximum is 100.
        field(
          :limit,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "limit", 'style': "form", 'explode': true}}
        )

        sig {
          params(
            organization_id: T.nilable(T.any(::String, T::Array[::String])),
            page: T.nilable(::Integer),
            limit: T.nilable(::Integer)
          )
            .void
        }
        def initialize(organization_id: nil, page: 1, limit: 10)
          @organization_id = organization_id
          @page = page
          @limit = limit
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @organization_id == other.organization_id
          return false unless @page == other.page
          return false unless @limit == other.limit
          true
        end
      end
    end
  end
end
