# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations

      class WebhooksGetWebhookEndpointResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # Successful Response
        field :webhook_endpoint, Crystalline::Nilable.new(Models::Components::WebhookEndpoint)

        sig {
          params(
            content_type: ::String,
            status_code: ::Integer,
            raw_response: ::Faraday::Response,
            webhook_endpoint: T.nilable(Models::Components::WebhookEndpoint)
          )
            .void
        }
        def initialize(content_type:, status_code:, raw_response:, webhook_endpoint: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @webhook_endpoint = webhook_endpoint
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @webhook_endpoint == other.webhook_endpoint
          true
        end
      end
    end
  end
end
